/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange
        //private AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange instance;

        public AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRangeTests()
        {
            // TODO uncomment below to create an instance of AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange
            //instance = new AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange
        /// </summary>
        [Fact]
        public void AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRangeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange
            //Assert.IsType<AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange>(instance);
        }

        /// <summary>
        /// Test the property 'StartDt'
        /// </summary>
        [Fact]
        public void StartDtTest()
        {
            // TODO unit test for the property 'StartDt'
        }

        /// <summary>
        /// Test the property 'EndDt'
        /// </summary>
        [Fact]
        public void EndDtTest()
        {
            // TODO unit test for the property 'EndDt'
        }

        /// <summary>
        /// Test the property 'YearMonth'
        /// </summary>
        [Fact]
        public void YearMonthTest()
        {
            // TODO unit test for the property 'YearMonth'
        }
    }
}
