/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmtTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmt
        //private AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmt instance;

        public AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmtTests()
        {
            // TODO uncomment below to create an instance of AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmt
            //instance = new AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmt
        /// </summary>
        [Fact]
        public void AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmtInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmt
            //Assert.IsType<AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoCurAmt>(instance);
        }

        /// <summary>
        /// Test the property 'Amt'
        /// </summary>
        [Fact]
        public void AmtTest()
        {
            // TODO unit test for the property 'Amt'
        }

        /// <summary>
        /// Test the property 'CurCode'
        /// </summary>
        [Fact]
        public void CurCodeTest()
        {
            // TODO unit test for the property 'CurCode'
        }
    }
}
