/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing AcctAcctTrnInqRequestAcctAcctTrnInqRq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcctAcctTrnInqRequestAcctAcctTrnInqRqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcctAcctTrnInqRequestAcctAcctTrnInqRq
        //private AcctAcctTrnInqRequestAcctAcctTrnInqRq instance;

        public AcctAcctTrnInqRequestAcctAcctTrnInqRqTests()
        {
            // TODO uncomment below to create an instance of AcctAcctTrnInqRequestAcctAcctTrnInqRq
            //instance = new AcctAcctTrnInqRequestAcctAcctTrnInqRq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcctAcctTrnInqRequestAcctAcctTrnInqRq
        /// </summary>
        [Fact]
        public void AcctAcctTrnInqRequestAcctAcctTrnInqRqInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcctAcctTrnInqRequestAcctAcctTrnInqRq
            //Assert.IsType<AcctAcctTrnInqRequestAcctAcctTrnInqRq>(instance);
        }

        /// <summary>
        /// Test the property 'RqUID'
        /// </summary>
        [Fact]
        public void RqUIDTest()
        {
            // TODO unit test for the property 'RqUID'
        }

        /// <summary>
        /// Test the property 'MsgRqHdr'
        /// </summary>
        [Fact]
        public void MsgRqHdrTest()
        {
            // TODO unit test for the property 'MsgRqHdr'
        }

        /// <summary>
        /// Test the property 'RecCtrlIn'
        /// </summary>
        [Fact]
        public void RecCtrlInTest()
        {
            // TODO unit test for the property 'RecCtrlIn'
        }

        /// <summary>
        /// Test the property 'AcctTrnSel'
        /// </summary>
        [Fact]
        public void AcctTrnSelTest()
        {
            // TODO unit test for the property 'AcctTrnSel'
        }
    }
}
