/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddr
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddrTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddr
        //private AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddr instance;

        public AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddrTests()
        {
            // TODO uncomment below to create an instance of AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddr
            //instance = new AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddr();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddr
        /// </summary>
        [Fact]
        public void AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddrInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddr
            //Assert.IsType<AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnEnvrAddressBranchAddr>(instance);
        }

        /// <summary>
        /// Test the property 'BranchNo'
        /// </summary>
        [Fact]
        public void BranchNoTest()
        {
            // TODO unit test for the property 'BranchNo'
        }

        /// <summary>
        /// Test the property 'OriginBranch'
        /// </summary>
        [Fact]
        public void OriginBranchTest()
        {
            // TODO unit test for the property 'OriginBranch'
        }

        /// <summary>
        /// Test the property 'BranchName'
        /// </summary>
        [Fact]
        public void BranchNameTest()
        {
            // TODO unit test for the property 'BranchName'
        }

        /// <summary>
        /// Test the property 'BrAddr1'
        /// </summary>
        [Fact]
        public void BrAddr1Test()
        {
            // TODO unit test for the property 'BrAddr1'
        }

        /// <summary>
        /// Test the property 'BrAddr2'
        /// </summary>
        [Fact]
        public void BrAddr2Test()
        {
            // TODO unit test for the property 'BrAddr2'
        }

        /// <summary>
        /// Test the property 'BrAddr3'
        /// </summary>
        [Fact]
        public void BrAddr3Test()
        {
            // TODO unit test for the property 'BrAddr3'
        }

        /// <summary>
        /// Test the property 'BrCity'
        /// </summary>
        [Fact]
        public void BrCityTest()
        {
            // TODO unit test for the property 'BrCity'
        }
    }
}
