/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdr
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdrTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdr
        //private AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdr instance;

        public AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdrTests()
        {
            // TODO uncomment below to create an instance of AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdr
            //instance = new AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdr();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdr
        /// </summary>
        [Fact]
        public void AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdrInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdr
            //Assert.IsType<AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdr>(instance);
        }

        /// <summary>
        /// Test the property 'CurCode'
        /// </summary>
        [Fact]
        public void CurCodeTest()
        {
            // TODO unit test for the property 'CurCode'
        }

        /// <summary>
        /// Test the property 'AcctBal'
        /// </summary>
        [Fact]
        public void AcctBalTest()
        {
            // TODO unit test for the property 'AcctBal'
        }

        /// <summary>
        /// Test the property 'AcctStatus'
        /// </summary>
        [Fact]
        public void AcctStatusTest()
        {
            // TODO unit test for the property 'AcctStatus'
        }

        /// <summary>
        /// Test the property 'AcctTitle'
        /// </summary>
        [Fact]
        public void AcctTitleTest()
        {
            // TODO unit test for the property 'AcctTitle'
        }
    }
}
