/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnType
        //private AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnType instance;

        public AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnTypeTests()
        {
            // TODO uncomment below to create an instance of AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnType
            //instance = new AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnType
        /// </summary>
        [Fact]
        public void AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnType
            //Assert.IsType<AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctTrnRecInnerAcctTrnInfoTrnType>(instance);
        }

        /// <summary>
        /// Test the property 'TrnTypeValue'
        /// </summary>
        [Fact]
        public void TrnTypeValueTest()
        {
            // TODO unit test for the property 'TrnTypeValue'
        }
    }
}
