/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing DdaEnquirydetailsResponseDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DdaEnquirydetailsResponseDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DdaEnquirydetailsResponseDataInner
        //private DdaEnquirydetailsResponseDataInner instance;

        public DdaEnquirydetailsResponseDataInnerTests()
        {
            // TODO uncomment below to create an instance of DdaEnquirydetailsResponseDataInner
            //instance = new DdaEnquirydetailsResponseDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DdaEnquirydetailsResponseDataInner
        /// </summary>
        [Fact]
        public void DdaEnquirydetailsResponseDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DdaEnquirydetailsResponseDataInner
            //Assert.IsType<DdaEnquirydetailsResponseDataInner>(instance);
        }

        /// <summary>
        /// Test the property 'ContractReferenceNumber'
        /// </summary>
        [Fact]
        public void ContractReferenceNumberTest()
        {
            // TODO unit test for the property 'ContractReferenceNumber'
        }

        /// <summary>
        /// Test the property 'InstructionCode'
        /// </summary>
        [Fact]
        public void InstructionCodeTest()
        {
            // TODO unit test for the property 'InstructionCode'
        }

        /// <summary>
        /// Test the property 'OIC'
        /// </summary>
        [Fact]
        public void OICTest()
        {
            // TODO unit test for the property 'OIC'
        }

        /// <summary>
        /// Test the property 'OriginatorName'
        /// </summary>
        [Fact]
        public void OriginatorNameTest()
        {
            // TODO unit test for the property 'OriginatorName'
        }

        /// <summary>
        /// Test the property 'PayerIdentNumberWithOrg'
        /// </summary>
        [Fact]
        public void PayerIdentNumberWithOrgTest()
        {
            // TODO unit test for the property 'PayerIdentNumberWithOrg'
        }

        /// <summary>
        /// Test the property 'CustomerType'
        /// </summary>
        [Fact]
        public void CustomerTypeTest()
        {
            // TODO unit test for the property 'CustomerType'
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

        /// <summary>
        /// Test the property 'DDAIssuedFor'
        /// </summary>
        [Fact]
        public void DDAIssuedForTest()
        {
            // TODO unit test for the property 'DDAIssuedFor'
        }

        /// <summary>
        /// Test the property 'PayingBankID'
        /// </summary>
        [Fact]
        public void PayingBankIDTest()
        {
            // TODO unit test for the property 'PayingBankID'
        }

        /// <summary>
        /// Test the property 'PayerName'
        /// </summary>
        [Fact]
        public void PayerNameTest()
        {
            // TODO unit test for the property 'PayerName'
        }

        /// <summary>
        /// Test the property 'PayerMobileNumber'
        /// </summary>
        [Fact]
        public void PayerMobileNumberTest()
        {
            // TODO unit test for the property 'PayerMobileNumber'
        }

        /// <summary>
        /// Test the property 'PayerEmailAddress'
        /// </summary>
        [Fact]
        public void PayerEmailAddressTest()
        {
            // TODO unit test for the property 'PayerEmailAddress'
        }

        /// <summary>
        /// Test the property 'FundingAccountType'
        /// </summary>
        [Fact]
        public void FundingAccountTypeTest()
        {
            // TODO unit test for the property 'FundingAccountType'
        }

        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }

        /// <summary>
        /// Test the property 'DDACommencementDate'
        /// </summary>
        [Fact]
        public void DDACommencementDateTest()
        {
            // TODO unit test for the property 'DDACommencementDate'
        }

        /// <summary>
        /// Test the property 'DebitRequestInstances'
        /// </summary>
        [Fact]
        public void DebitRequestInstancesTest()
        {
            // TODO unit test for the property 'DebitRequestInstances'
        }

        /// <summary>
        /// Test the property 'DDAExpiryDate'
        /// </summary>
        [Fact]
        public void DDAExpiryDateTest()
        {
            // TODO unit test for the property 'DDAExpiryDate'
        }

        /// <summary>
        /// Test the property 'DDAAmountType'
        /// </summary>
        [Fact]
        public void DDAAmountTypeTest()
        {
            // TODO unit test for the property 'DDAAmountType'
        }

        /// <summary>
        /// Test the property 'PaymentFrequency'
        /// </summary>
        [Fact]
        public void PaymentFrequencyTest()
        {
            // TODO unit test for the property 'PaymentFrequency'
        }

        /// <summary>
        /// Test the property 'DDRDefinedDays'
        /// </summary>
        [Fact]
        public void DDRDefinedDaysTest()
        {
            // TODO unit test for the property 'DDRDefinedDays'
        }

        /// <summary>
        /// Test the property 'DDMinimumAmount'
        /// </summary>
        [Fact]
        public void DDMinimumAmountTest()
        {
            // TODO unit test for the property 'DDMinimumAmount'
        }

        /// <summary>
        /// Test the property 'DDMaximumAmount'
        /// </summary>
        [Fact]
        public void DDMaximumAmountTest()
        {
            // TODO unit test for the property 'DDMaximumAmount'
        }

        /// <summary>
        /// Test the property 'CaptureMode'
        /// </summary>
        [Fact]
        public void CaptureModeTest()
        {
            // TODO unit test for the property 'CaptureMode'
        }

        /// <summary>
        /// Test the property 'DDAReferenceNumber'
        /// </summary>
        [Fact]
        public void DDAReferenceNumberTest()
        {
            // TODO unit test for the property 'DDAReferenceNumber'
        }

        /// <summary>
        /// Test the property 'ScannedDDAFileName'
        /// </summary>
        [Fact]
        public void ScannedDDAFileNameTest()
        {
            // TODO unit test for the property 'ScannedDDAFileName'
        }

        /// <summary>
        /// Test the property 'DDAStatus'
        /// </summary>
        [Fact]
        public void DDAStatusTest()
        {
            // TODO unit test for the property 'DDAStatus'
        }

        /// <summary>
        /// Test the property 'DDAPuposeCodeDesc'
        /// </summary>
        [Fact]
        public void DDAPuposeCodeDescTest()
        {
            // TODO unit test for the property 'DDAPuposeCodeDesc'
        }

        /// <summary>
        /// Test the property 'DDAType'
        /// </summary>
        [Fact]
        public void DDATypeTest()
        {
            // TODO unit test for the property 'DDAType'
        }
    }
}
