/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetRimInfoRequestGetRimInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetRimInfoRequestGetRimInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetRimInfoRequestGetRimInfo
        //private GetRimInfoRequestGetRimInfo instance;

        public GetRimInfoRequestGetRimInfoTests()
        {
            // TODO uncomment below to create an instance of GetRimInfoRequestGetRimInfo
            //instance = new GetRimInfoRequestGetRimInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetRimInfoRequestGetRimInfo
        /// </summary>
        [Fact]
        public void GetRimInfoRequestGetRimInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetRimInfoRequestGetRimInfo
            //Assert.IsType<GetRimInfoRequestGetRimInfo>(instance);
        }

        /// <summary>
        /// Test the property 'RimNo'
        /// </summary>
        [Fact]
        public void RimNoTest()
        {
            // TODO unit test for the property 'RimNo'
        }

        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Fact]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'FuncId'
        /// </summary>
        [Fact]
        public void FuncIdTest()
        {
            // TODO unit test for the property 'FuncId'
        }
    }
}
