/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetRimInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetRimInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetRimInfoResponse
        //private GetRimInfoResponse instance;

        public GetRimInfoResponseTests()
        {
            // TODO uncomment below to create an instance of GetRimInfoResponse
            //instance = new GetRimInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetRimInfoResponse
        /// </summary>
        [Fact]
        public void GetRimInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetRimInfoResponse
            //Assert.IsType<GetRimInfoResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
