/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartyinqrsCreditRiskType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyinqrsCreditRiskTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyinqrsCreditRiskType
        //private PartyinqrsCreditRiskType instance;

        public PartyinqrsCreditRiskTypeTests()
        {
            // TODO uncomment below to create an instance of PartyinqrsCreditRiskType
            //instance = new PartyinqrsCreditRiskType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyinqrsCreditRiskType
        /// </summary>
        [Fact]
        public void PartyinqrsCreditRiskTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyinqrsCreditRiskType
            //Assert.IsType<PartyinqrsCreditRiskType>(instance);
        }

        /// <summary>
        /// Test the property 'RiskCategory'
        /// </summary>
        [Fact]
        public void RiskCategoryTest()
        {
            // TODO unit test for the property 'RiskCategory'
        }

        /// <summary>
        /// Test the property 'InternalScore'
        /// </summary>
        [Fact]
        public void InternalScoreTest()
        {
            // TODO unit test for the property 'InternalScore'
        }

        /// <summary>
        /// Test the property 'ScoreGeneratedDt'
        /// </summary>
        [Fact]
        public void ScoreGeneratedDtTest()
        {
            // TODO unit test for the property 'ScoreGeneratedDt'
        }
    }
}
