/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartyinqrsPartyInqRs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyinqrsPartyInqRsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyinqrsPartyInqRs
        //private PartyinqrsPartyInqRs instance;

        public PartyinqrsPartyInqRsTests()
        {
            // TODO uncomment below to create an instance of PartyinqrsPartyInqRs
            //instance = new PartyinqrsPartyInqRs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyinqrsPartyInqRs
        /// </summary>
        [Fact]
        public void PartyinqrsPartyInqRsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyinqrsPartyInqRs
            //Assert.IsType<PartyinqrsPartyInqRs>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'RqUID'
        /// </summary>
        [Fact]
        public void RqUIDTest()
        {
            // TODO unit test for the property 'RqUID'
        }

        /// <summary>
        /// Test the property 'PartyRec'
        /// </summary>
        [Fact]
        public void PartyRecTest()
        {
            // TODO unit test for the property 'PartyRec'
        }

        /// <summary>
        /// Test the property 'OrgPartyRec'
        /// </summary>
        [Fact]
        public void OrgPartyRecTest()
        {
            // TODO unit test for the property 'OrgPartyRec'
        }
    }
}
