/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsPhoneType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsPhoneTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsPhoneType
        //private PartacctrelrsPhoneType instance;

        public PartacctrelrsPhoneTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsPhoneType
            //instance = new PartacctrelrsPhoneType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsPhoneType
        /// </summary>
        [Fact]
        public void PartacctrelrsPhoneTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsPhoneType
            //Assert.IsType<PartacctrelrsPhoneType>(instance);
        }

        /// <summary>
        /// Test the property 'PhoneType'
        /// </summary>
        [Fact]
        public void PhoneTypeTest()
        {
            // TODO unit test for the property 'PhoneType'
        }

        /// <summary>
        /// Test the property 'PhoneNum'
        /// </summary>
        [Fact]
        public void PhoneNumTest()
        {
            // TODO unit test for the property 'PhoneNum'
        }
    }
}
