/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartyInqResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyInqResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyInqResponse
        //private PartyInqResponse instance;

        public PartyInqResponseTests()
        {
            // TODO uncomment below to create an instance of PartyInqResponse
            //instance = new PartyInqResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyInqResponse
        /// </summary>
        [Fact]
        public void PartyInqResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyInqResponse
            //Assert.IsType<PartyInqResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PartyInqRs'
        /// </summary>
        [Fact]
        public void PartyInqRsTest()
        {
            // TODO unit test for the property 'PartyInqRs'
        }
    }
}
