/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsLoanAcctInfoType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsLoanAcctInfoTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsLoanAcctInfoType
        //private PartacctrelrsLoanAcctInfoType instance;

        public PartacctrelrsLoanAcctInfoTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsLoanAcctInfoType
            //instance = new PartacctrelrsLoanAcctInfoType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsLoanAcctInfoType
        /// </summary>
        [Fact]
        public void PartacctrelrsLoanAcctInfoTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsLoanAcctInfoType
            //Assert.IsType<PartacctrelrsLoanAcctInfoType>(instance);
        }

        /// <summary>
        /// Test the property 'PartyRef'
        /// </summary>
        [Fact]
        public void PartyRefTest()
        {
            // TODO unit test for the property 'PartyRef'
        }

        /// <summary>
        /// Test the property 'PartyRelRef'
        /// </summary>
        [Fact]
        public void PartyRelRefTest()
        {
            // TODO unit test for the property 'PartyRelRef'
        }

        /// <summary>
        /// Test the property 'CurCode'
        /// </summary>
        [Fact]
        public void CurCodeTest()
        {
            // TODO unit test for the property 'CurCode'
        }

        /// <summary>
        /// Test the property 'FIData'
        /// </summary>
        [Fact]
        public void FIDataTest()
        {
            // TODO unit test for the property 'FIData'
        }

        /// <summary>
        /// Test the property 'LoanAcctType'
        /// </summary>
        [Fact]
        public void LoanAcctTypeTest()
        {
            // TODO unit test for the property 'LoanAcctType'
        }

        /// <summary>
        /// Test the property 'AcctKeys'
        /// </summary>
        [Fact]
        public void AcctKeysTest()
        {
            // TODO unit test for the property 'AcctKeys'
        }

        /// <summary>
        /// Test the property 'LoanAcctKeys'
        /// </summary>
        [Fact]
        public void LoanAcctKeysTest()
        {
            // TODO unit test for the property 'LoanAcctKeys'
        }

        /// <summary>
        /// Test the property 'AcctStatus'
        /// </summary>
        [Fact]
        public void AcctStatusTest()
        {
            // TODO unit test for the property 'AcctStatus'
        }

        /// <summary>
        /// Test the property 'AcctTitle'
        /// </summary>
        [Fact]
        public void AcctTitleTest()
        {
            // TODO unit test for the property 'AcctTitle'
        }

        /// <summary>
        /// Test the property 'OpenDt'
        /// </summary>
        [Fact]
        public void OpenDtTest()
        {
            // TODO unit test for the property 'OpenDt'
        }

        /// <summary>
        /// Test the property 'MaturityDt'
        /// </summary>
        [Fact]
        public void MaturityDtTest()
        {
            // TODO unit test for the property 'MaturityDt'
        }

        /// <summary>
        /// Test the property 'AcctBal'
        /// </summary>
        [Fact]
        public void AcctBalTest()
        {
            // TODO unit test for the property 'AcctBal'
        }

        /// <summary>
        /// Test the property 'AcctClass'
        /// </summary>
        [Fact]
        public void AcctClassTest()
        {
            // TODO unit test for the property 'AcctClass'
        }

        /// <summary>
        /// Test the property 'IntRateData'
        /// </summary>
        [Fact]
        public void IntRateDataTest()
        {
            // TODO unit test for the property 'IntRateData'
        }

        /// <summary>
        /// Test the property 'NextIntData'
        /// </summary>
        [Fact]
        public void NextIntDataTest()
        {
            // TODO unit test for the property 'NextIntData'
        }

        /// <summary>
        /// Test the property 'InstData'
        /// </summary>
        [Fact]
        public void InstDataTest()
        {
            // TODO unit test for the property 'InstData'
        }

        /// <summary>
        /// Test the property 'Islamic'
        /// </summary>
        [Fact]
        public void IslamicTest()
        {
            // TODO unit test for the property 'Islamic'
        }

        /// <summary>
        /// Test the property 'Classified'
        /// </summary>
        [Fact]
        public void ClassifiedTest()
        {
            // TODO unit test for the property 'Classified'
        }
    }
}
