/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartyinqrqPartyKeysType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyinqrqPartyKeysTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyinqrqPartyKeysType
        //private PartyinqrqPartyKeysType instance;

        public PartyinqrqPartyKeysTypeTests()
        {
            // TODO uncomment below to create an instance of PartyinqrqPartyKeysType
            //instance = new PartyinqrqPartyKeysType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyinqrqPartyKeysType
        /// </summary>
        [Fact]
        public void PartyinqrqPartyKeysTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyinqrqPartyKeysType
            //Assert.IsType<PartyinqrqPartyKeysType>(instance);
        }

        /// <summary>
        /// Test the property 'PartyId'
        /// </summary>
        [Fact]
        public void PartyIdTest()
        {
            // TODO unit test for the property 'PartyId'
        }

        /// <summary>
        /// Test the property 'PartyPartyRelId'
        /// </summary>
        [Fact]
        public void PartyPartyRelIdTest()
        {
            // TODO unit test for the property 'PartyPartyRelId'
        }
    }
}
