/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartyInqRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyInqRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyInqRequest
        //private PartyInqRequest instance;

        public PartyInqRequestTests()
        {
            // TODO uncomment below to create an instance of PartyInqRequest
            //instance = new PartyInqRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyInqRequest
        /// </summary>
        [Fact]
        public void PartyInqRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyInqRequest
            //Assert.IsType<PartyInqRequest>(instance);
        }

        /// <summary>
        /// Test the property 'PartyInqRq'
        /// </summary>
        [Fact]
        public void PartyInqRqTest()
        {
            // TODO unit test for the property 'PartyInqRq'
        }
    }
}
