/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsNumInstsType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsNumInstsTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsNumInstsType
        //private PartacctrelrsNumInstsType instance;

        public PartacctrelrsNumInstsTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsNumInstsType
            //instance = new PartacctrelrsNumInstsType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsNumInstsType
        /// </summary>
        [Fact]
        public void PartacctrelrsNumInstsTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsNumInstsType
            //Assert.IsType<PartacctrelrsNumInstsType>(instance);
        }

        /// <summary>
        /// Test the property 'NextInstAmt'
        /// </summary>
        [Fact]
        public void NextInstAmtTest()
        {
            // TODO unit test for the property 'NextInstAmt'
        }

        /// <summary>
        /// Test the property 'NextInstDt'
        /// </summary>
        [Fact]
        public void NextInstDtTest()
        {
            // TODO unit test for the property 'NextInstDt'
        }

        /// <summary>
        /// Test the property 'LastDueAmt'
        /// </summary>
        [Fact]
        public void LastDueAmtTest()
        {
            // TODO unit test for the property 'LastDueAmt'
        }

        /// <summary>
        /// Test the property 'LastDueDt'
        /// </summary>
        [Fact]
        public void LastDueDtTest()
        {
            // TODO unit test for the property 'LastDueDt'
        }

        /// <summary>
        /// Test the property 'TotalPmtCount'
        /// </summary>
        [Fact]
        public void TotalPmtCountTest()
        {
            // TODO unit test for the property 'TotalPmtCount'
        }

        /// <summary>
        /// Test the property 'RemainingPmtCount'
        /// </summary>
        [Fact]
        public void RemainingPmtCountTest()
        {
            // TODO unit test for the property 'RemainingPmtCount'
        }
    }
}
