/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartyinqrsFatcaDetailsType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyinqrsFatcaDetailsTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyinqrsFatcaDetailsType
        //private PartyinqrsFatcaDetailsType instance;

        public PartyinqrsFatcaDetailsTypeTests()
        {
            // TODO uncomment below to create an instance of PartyinqrsFatcaDetailsType
            //instance = new PartyinqrsFatcaDetailsType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyinqrsFatcaDetailsType
        /// </summary>
        [Fact]
        public void PartyinqrsFatcaDetailsTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyinqrsFatcaDetailsType
            //Assert.IsType<PartyinqrsFatcaDetailsType>(instance);
        }

        /// <summary>
        /// Test the property 'TIN'
        /// </summary>
        [Fact]
        public void TINTest()
        {
            // TODO unit test for the property 'TIN'
        }

        /// <summary>
        /// Test the property 'SSN'
        /// </summary>
        [Fact]
        public void SSNTest()
        {
            // TODO unit test for the property 'SSN'
        }

        /// <summary>
        /// Test the property 'USResidentStatus'
        /// </summary>
        [Fact]
        public void USResidentStatusTest()
        {
            // TODO unit test for the property 'USResidentStatus'
        }
    }
}
