/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsPartyAcctRelRecType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsPartyAcctRelRecTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsPartyAcctRelRecType
        //private PartacctrelrsPartyAcctRelRecType instance;

        public PartacctrelrsPartyAcctRelRecTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsPartyAcctRelRecType
            //instance = new PartacctrelrsPartyAcctRelRecType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsPartyAcctRelRecType
        /// </summary>
        [Fact]
        public void PartacctrelrsPartyAcctRelRecTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsPartyAcctRelRecType
            //Assert.IsType<PartacctrelrsPartyAcctRelRecType>(instance);
        }

        /// <summary>
        /// Test the property 'PartyAcctRelInfo'
        /// </summary>
        [Fact]
        public void PartyAcctRelInfoTest()
        {
            // TODO unit test for the property 'PartyAcctRelInfo'
        }
    }
}
