/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartyinqrsFinancialDataType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyinqrsFinancialDataTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyinqrsFinancialDataType
        //private PartyinqrsFinancialDataType instance;

        public PartyinqrsFinancialDataTypeTests()
        {
            // TODO uncomment below to create an instance of PartyinqrsFinancialDataType
            //instance = new PartyinqrsFinancialDataType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyinqrsFinancialDataType
        /// </summary>
        [Fact]
        public void PartyinqrsFinancialDataTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyinqrsFinancialDataType
            //Assert.IsType<PartyinqrsFinancialDataType>(instance);
        }

        /// <summary>
        /// Test the property 'FinancialType'
        /// </summary>
        [Fact]
        public void FinancialTypeTest()
        {
            // TODO unit test for the property 'FinancialType'
        }

        /// <summary>
        /// Test the property 'FinancialAmt'
        /// </summary>
        [Fact]
        public void FinancialAmtTest()
        {
            // TODO unit test for the property 'FinancialAmt'
        }

        /// <summary>
        /// Test the property 'RelEstablishedDt'
        /// </summary>
        [Fact]
        public void RelEstablishedDtTest()
        {
            // TODO unit test for the property 'RelEstablishedDt'
        }

        /// <summary>
        /// Test the property 'IncomeCurrency'
        /// </summary>
        [Fact]
        public void IncomeCurrencyTest()
        {
            // TODO unit test for the property 'IncomeCurrency'
        }
    }
}
