/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsPartyRelRefType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsPartyRelRefTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsPartyRelRefType
        //private PartacctrelrsPartyRelRefType instance;

        public PartacctrelrsPartyRelRefTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsPartyRelRefType
            //instance = new PartacctrelrsPartyRelRefType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsPartyRelRefType
        /// </summary>
        [Fact]
        public void PartacctrelrsPartyRelRefTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsPartyRelRefType
            //Assert.IsType<PartacctrelrsPartyRelRefType>(instance);
        }

        /// <summary>
        /// Test the property 'PartyRelType'
        /// </summary>
        [Fact]
        public void PartyRelTypeTest()
        {
            // TODO unit test for the property 'PartyRelType'
        }

        /// <summary>
        /// Test the property 'PartyKeys'
        /// </summary>
        [Fact]
        public void PartyKeysTest()
        {
            // TODO unit test for the property 'PartyKeys'
        }

        /// <summary>
        /// Test the property 'PersonName'
        /// </summary>
        [Fact]
        public void PersonNameTest()
        {
            // TODO unit test for the property 'PersonName'
        }
    }
}
