/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartyinqrsPostAddrType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyinqrsPostAddrTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyinqrsPostAddrType
        //private PartyinqrsPostAddrType instance;

        public PartyinqrsPostAddrTypeTests()
        {
            // TODO uncomment below to create an instance of PartyinqrsPostAddrType
            //instance = new PartyinqrsPostAddrType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyinqrsPostAddrType
        /// </summary>
        [Fact]
        public void PartyinqrsPostAddrTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyinqrsPostAddrType
            //Assert.IsType<PartyinqrsPostAddrType>(instance);
        }

        /// <summary>
        /// Test the property 'AddressIdent'
        /// </summary>
        [Fact]
        public void AddressIdentTest()
        {
            // TODO unit test for the property 'AddressIdent'
        }

        /// <summary>
        /// Test the property 'Addr1'
        /// </summary>
        [Fact]
        public void Addr1Test()
        {
            // TODO unit test for the property 'Addr1'
        }

        /// <summary>
        /// Test the property 'Addr2'
        /// </summary>
        [Fact]
        public void Addr2Test()
        {
            // TODO unit test for the property 'Addr2'
        }

        /// <summary>
        /// Test the property 'Addr3'
        /// </summary>
        [Fact]
        public void Addr3Test()
        {
            // TODO unit test for the property 'Addr3'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
    }
}
