/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsAcctInfoType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsAcctInfoTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsAcctInfoType
        //private PartacctrelrsAcctInfoType instance;

        public PartacctrelrsAcctInfoTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsAcctInfoType
            //instance = new PartacctrelrsAcctInfoType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsAcctInfoType
        /// </summary>
        [Fact]
        public void PartacctrelrsAcctInfoTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsAcctInfoType
            //Assert.IsType<PartacctrelrsAcctInfoType>(instance);
        }

        /// <summary>
        /// Test the property 'CurCode'
        /// </summary>
        [Fact]
        public void CurCodeTest()
        {
            // TODO unit test for the property 'CurCode'
        }

        /// <summary>
        /// Test the property 'IBAN'
        /// </summary>
        [Fact]
        public void IBANTest()
        {
            // TODO unit test for the property 'IBAN'
        }

        /// <summary>
        /// Test the property 'FIData'
        /// </summary>
        [Fact]
        public void FIDataTest()
        {
            // TODO unit test for the property 'FIData'
        }

        /// <summary>
        /// Test the property 'AcctType'
        /// </summary>
        [Fact]
        public void AcctTypeTest()
        {
            // TODO unit test for the property 'AcctType'
        }

        /// <summary>
        /// Test the property 'AcctTitle'
        /// </summary>
        [Fact]
        public void AcctTitleTest()
        {
            // TODO unit test for the property 'AcctTitle'
        }

        /// <summary>
        /// Test the property 'OpenDt'
        /// </summary>
        [Fact]
        public void OpenDtTest()
        {
            // TODO unit test for the property 'OpenDt'
        }

        /// <summary>
        /// Test the property 'MaturityDt'
        /// </summary>
        [Fact]
        public void MaturityDtTest()
        {
            // TODO unit test for the property 'MaturityDt'
        }

        /// <summary>
        /// Test the property 'AcctBal'
        /// </summary>
        [Fact]
        public void AcctBalTest()
        {
            // TODO unit test for the property 'AcctBal'
        }

        /// <summary>
        /// Test the property 'Segmentation'
        /// </summary>
        [Fact]
        public void SegmentationTest()
        {
            // TODO unit test for the property 'Segmentation'
        }

        /// <summary>
        /// Test the property 'AcctClass'
        /// </summary>
        [Fact]
        public void AcctClassTest()
        {
            // TODO unit test for the property 'AcctClass'
        }

        /// <summary>
        /// Test the property 'StmtPeriod'
        /// </summary>
        [Fact]
        public void StmtPeriodTest()
        {
            // TODO unit test for the property 'StmtPeriod'
        }

        /// <summary>
        /// Test the property 'IntRateData'
        /// </summary>
        [Fact]
        public void IntRateDataTest()
        {
            // TODO unit test for the property 'IntRateData'
        }

        /// <summary>
        /// Test the property 'AcctPeriodData'
        /// </summary>
        [Fact]
        public void AcctPeriodDataTest()
        {
            // TODO unit test for the property 'AcctPeriodData'
        }

        /// <summary>
        /// Test the property 'AcctTrnLimit'
        /// </summary>
        [Fact]
        public void AcctTrnLimitTest()
        {
            // TODO unit test for the property 'AcctTrnLimit'
        }

        /// <summary>
        /// Test the property 'SalaryTransfer'
        /// </summary>
        [Fact]
        public void SalaryTransferTest()
        {
            // TODO unit test for the property 'SalaryTransfer'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'PostDt'
        /// </summary>
        [Fact]
        public void PostDtTest()
        {
            // TODO unit test for the property 'PostDt'
        }

        /// <summary>
        /// Test the property 'ValueDt'
        /// </summary>
        [Fact]
        public void ValueDtTest()
        {
            // TODO unit test for the property 'ValueDt'
        }

        /// <summary>
        /// Test the property 'ChkNo'
        /// </summary>
        [Fact]
        public void ChkNoTest()
        {
            // TODO unit test for the property 'ChkNo'
        }
    }
}
