/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsAcctStatusType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsAcctStatusTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsAcctStatusType
        //private PartacctrelrsAcctStatusType instance;

        public PartacctrelrsAcctStatusTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsAcctStatusType
            //instance = new PartacctrelrsAcctStatusType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsAcctStatusType
        /// </summary>
        [Fact]
        public void PartacctrelrsAcctStatusTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsAcctStatusType
            //Assert.IsType<PartacctrelrsAcctStatusType>(instance);
        }

        /// <summary>
        /// Test the property 'AcctStatusCode'
        /// </summary>
        [Fact]
        public void AcctStatusCodeTest()
        {
            // TODO unit test for the property 'AcctStatusCode'
        }

        /// <summary>
        /// Test the property 'AcctStatusDesc'
        /// </summary>
        [Fact]
        public void AcctStatusDescTest()
        {
            // TODO unit test for the property 'AcctStatusDesc'
        }
    }
}
