/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsIntRateDataType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsIntRateDataTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsIntRateDataType
        //private PartacctrelrsIntRateDataType instance;

        public PartacctrelrsIntRateDataTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsIntRateDataType
            //instance = new PartacctrelrsIntRateDataType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsIntRateDataType
        /// </summary>
        [Fact]
        public void PartacctrelrsIntRateDataTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsIntRateDataType
            //Assert.IsType<PartacctrelrsIntRateDataType>(instance);
        }

        /// <summary>
        /// Test the property 'IntRate'
        /// </summary>
        [Fact]
        public void IntRateTest()
        {
            // TODO unit test for the property 'IntRate'
        }

        /// <summary>
        /// Test the property 'CurAmt'
        /// </summary>
        [Fact]
        public void CurAmtTest()
        {
            // TODO unit test for the property 'CurAmt'
        }
    }
}
