/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing PartacctrelrsAcctEnvrType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartacctrelrsAcctEnvrTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartacctrelrsAcctEnvrType
        //private PartacctrelrsAcctEnvrType instance;

        public PartacctrelrsAcctEnvrTypeTests()
        {
            // TODO uncomment below to create an instance of PartacctrelrsAcctEnvrType
            //instance = new PartacctrelrsAcctEnvrType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartacctrelrsAcctEnvrType
        /// </summary>
        [Fact]
        public void PartacctrelrsAcctEnvrTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartacctrelrsAcctEnvrType
            //Assert.IsType<PartacctrelrsAcctEnvrType>(instance);
        }

        /// <summary>
        /// Test the property 'ChkBkInd'
        /// </summary>
        [Fact]
        public void ChkBkIndTest()
        {
            // TODO unit test for the property 'ChkBkInd'
        }

        /// <summary>
        /// Test the property 'IslamicInd'
        /// </summary>
        [Fact]
        public void IslamicIndTest()
        {
            // TODO unit test for the property 'IslamicInd'
        }

        /// <summary>
        /// Test the property 'IssuedIdent'
        /// </summary>
        [Fact]
        public void IssuedIdentTest()
        {
            // TODO unit test for the property 'IssuedIdent'
        }
    }
}
