/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitStatInqRqRemitStatInqRqRemitStatSel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitStatInqRqRemitStatInqRqRemitStatSelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitStatInqRqRemitStatInqRqRemitStatSel
        //private RemitStatInqRqRemitStatInqRqRemitStatSel instance;

        public RemitStatInqRqRemitStatInqRqRemitStatSelTests()
        {
            // TODO uncomment below to create an instance of RemitStatInqRqRemitStatInqRqRemitStatSel
            //instance = new RemitStatInqRqRemitStatInqRqRemitStatSel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitStatInqRqRemitStatInqRqRemitStatSel
        /// </summary>
        [Fact]
        public void RemitStatInqRqRemitStatInqRqRemitStatSelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitStatInqRqRemitStatInqRqRemitStatSel
            //Assert.IsType<RemitStatInqRqRemitStatInqRqRemitStatSel>(instance);
        }

        /// <summary>
        /// Test the property 'RemitId'
        /// </summary>
        [Fact]
        public void RemitIdTest()
        {
            // TODO unit test for the property 'RemitId'
        }

        /// <summary>
        /// Test the property 'RemitMode'
        /// </summary>
        [Fact]
        public void RemitModeTest()
        {
            // TODO unit test for the property 'RemitMode'
        }
    }
}
