/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatus
        //private RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatus instance;

        public RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatusTests()
        {
            // TODO uncomment below to create an instance of RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatus
            //instance = new RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatus
        /// </summary>
        [Fact]
        public void RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatus
            //Assert.IsType<RemitStatInqRsRemitStatInqRsRemitStatusRecRemitStatus>(instance);
        }

        /// <summary>
        /// Test the property 'RemitStatusCode'
        /// </summary>
        [Fact]
        public void RemitStatusCodeTest()
        {
            // TODO unit test for the property 'RemitStatusCode'
        }

        /// <summary>
        /// Test the property 'EffDt'
        /// </summary>
        [Fact]
        public void EffDtTest()
        {
            // TODO unit test for the property 'EffDt'
        }

        /// <summary>
        /// Test the property 'RemitStatusDesc'
        /// </summary>
        [Fact]
        public void RemitStatusDescTest()
        {
            // TODO unit test for the property 'RemitStatusDesc'
        }
    }
}
