/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitStatInqRqRemitStatInqRq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitStatInqRqRemitStatInqRqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitStatInqRqRemitStatInqRq
        //private RemitStatInqRqRemitStatInqRq instance;

        public RemitStatInqRqRemitStatInqRqTests()
        {
            // TODO uncomment below to create an instance of RemitStatInqRqRemitStatInqRq
            //instance = new RemitStatInqRqRemitStatInqRq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitStatInqRqRemitStatInqRq
        /// </summary>
        [Fact]
        public void RemitStatInqRqRemitStatInqRqInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitStatInqRqRemitStatInqRq
            //Assert.IsType<RemitStatInqRqRemitStatInqRq>(instance);
        }

        /// <summary>
        /// Test the property 'RqUID'
        /// </summary>
        [Fact]
        public void RqUIDTest()
        {
            // TODO unit test for the property 'RqUID'
        }

        /// <summary>
        /// Test the property 'MsgRqHdr'
        /// </summary>
        [Fact]
        public void MsgRqHdrTest()
        {
            // TODO unit test for the property 'MsgRqHdr'
        }

        /// <summary>
        /// Test the property 'RemitStatSel'
        /// </summary>
        [Fact]
        public void RemitStatSelTest()
        {
            // TODO unit test for the property 'RemitStatSel'
        }
    }
}
