/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAlloc
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAlloc
        //private RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAlloc instance;

        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocTests()
        {
            // TODO uncomment below to create an instance of RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAlloc
            //instance = new RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAlloc();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAlloc
        /// </summary>
        [Fact]
        public void RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAlloc
            //Assert.IsType<RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAlloc>(instance);
        }

        /// <summary>
        /// Test the property 'ChargeRegulation'
        /// </summary>
        [Fact]
        public void ChargeRegulationTest()
        {
            // TODO unit test for the property 'ChargeRegulation'
        }

        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }

        /// <summary>
        /// Test the property 'AcctKeys'
        /// </summary>
        [Fact]
        public void AcctKeysTest()
        {
            // TODO unit test for the property 'AcctKeys'
        }

        /// <summary>
        /// Test the property 'SegmentCode'
        /// </summary>
        [Fact]
        public void SegmentCodeTest()
        {
            // TODO unit test for the property 'SegmentCode'
        }

        /// <summary>
        /// Test the property 'FeeDesc'
        /// </summary>
        [Fact]
        public void FeeDescTest()
        {
            // TODO unit test for the property 'FeeDesc'
        }

        /// <summary>
        /// Test the property 'ChargeCode'
        /// </summary>
        [Fact]
        public void ChargeCodeTest()
        {
            // TODO unit test for the property 'ChargeCode'
        }
    }
}
