/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo
        //private RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo instance;

        public RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfoTests()
        {
            // TODO uncomment below to create an instance of RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo
            //instance = new RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo
        /// </summary>
        [Fact]
        public void RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo
            //Assert.IsType<RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo>(instance);
        }

        /// <summary>
        /// Test the property 'ForExQuoteRef'
        /// </summary>
        [Fact]
        public void ForExQuoteRefTest()
        {
            // TODO unit test for the property 'ForExQuoteRef'
        }
    }
}
