/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitAddResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitAddResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitAddResponse
        //private RemitAddResponse instance;

        public RemitAddResponseTests()
        {
            // TODO uncomment below to create an instance of RemitAddResponse
            //instance = new RemitAddResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitAddResponse
        /// </summary>
        [Fact]
        public void RemitAddResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitAddResponse
            //Assert.IsType<RemitAddResponse>(instance);
        }

        /// <summary>
        /// Test the property 'RemitAddRs'
        /// </summary>
        [Fact]
        public void RemitAddRsTest()
        {
            // TODO unit test for the property 'RemitAddRs'
        }
    }
}
