/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitAddResponseRemitAddRsRemitRecRemitInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitAddResponseRemitAddRsRemitRecRemitInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitAddResponseRemitAddRsRemitRecRemitInfo
        //private RemitAddResponseRemitAddRsRemitRecRemitInfo instance;

        public RemitAddResponseRemitAddRsRemitRecRemitInfoTests()
        {
            // TODO uncomment below to create an instance of RemitAddResponseRemitAddRsRemitRecRemitInfo
            //instance = new RemitAddResponseRemitAddRsRemitRecRemitInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitAddResponseRemitAddRsRemitRecRemitInfo
        /// </summary>
        [Fact]
        public void RemitAddResponseRemitAddRsRemitRecRemitInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitAddResponseRemitAddRsRemitRecRemitInfo
            //Assert.IsType<RemitAddResponseRemitAddRsRemitRecRemitInfo>(instance);
        }

        /// <summary>
        /// Test the property 'DebitRef'
        /// </summary>
        [Fact]
        public void DebitRefTest()
        {
            // TODO unit test for the property 'DebitRef'
        }

        /// <summary>
        /// Test the property 'CreditRef'
        /// </summary>
        [Fact]
        public void CreditRefTest()
        {
            // TODO unit test for the property 'CreditRef'
        }

        /// <summary>
        /// Test the property 'FeeChargeAlloc'
        /// </summary>
        [Fact]
        public void FeeChargeAllocTest()
        {
            // TODO unit test for the property 'FeeChargeAlloc'
        }

        /// <summary>
        /// Test the property 'ForExDealRef'
        /// </summary>
        [Fact]
        public void ForExDealRefTest()
        {
            // TODO unit test for the property 'ForExDealRef'
        }
    }
}
