/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitAddRequestRemitAddRqMsgRqHdr
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitAddRequestRemitAddRqMsgRqHdrTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitAddRequestRemitAddRqMsgRqHdr
        //private RemitAddRequestRemitAddRqMsgRqHdr instance;

        public RemitAddRequestRemitAddRqMsgRqHdrTests()
        {
            // TODO uncomment below to create an instance of RemitAddRequestRemitAddRqMsgRqHdr
            //instance = new RemitAddRequestRemitAddRqMsgRqHdr();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitAddRequestRemitAddRqMsgRqHdr
        /// </summary>
        [Fact]
        public void RemitAddRequestRemitAddRqMsgRqHdrInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitAddRequestRemitAddRqMsgRqHdr
            //Assert.IsType<RemitAddRequestRemitAddRqMsgRqHdr>(instance);
        }

        /// <summary>
        /// Test the property 'SvcIdent'
        /// </summary>
        [Fact]
        public void SvcIdentTest()
        {
            // TODO unit test for the property 'SvcIdent'
        }

        /// <summary>
        /// Test the property 'CredentialsRqHdr'
        /// </summary>
        [Fact]
        public void CredentialsRqHdrTest()
        {
            // TODO unit test for the property 'CredentialsRqHdr'
        }
    }
}
