/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitStatInqRs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitStatInqRsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitStatInqRs
        //private RemitStatInqRs instance;

        public RemitStatInqRsTests()
        {
            // TODO uncomment below to create an instance of RemitStatInqRs
            //instance = new RemitStatInqRs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitStatInqRs
        /// </summary>
        [Fact]
        public void RemitStatInqRsInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitStatInqRs
            //Assert.IsType<RemitStatInqRs>(instance);
        }

        /// <summary>
        /// Test the property 'VarRemitStatInqRs'
        /// </summary>
        [Fact]
        public void VarRemitStatInqRsTest()
        {
            // TODO unit test for the property 'VarRemitStatInqRs'
        }
    }
}
