/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFee
        //private RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFee instance;

        public RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFeeTests()
        {
            // TODO uncomment below to create an instance of RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFee
            //instance = new RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFee
        /// </summary>
        [Fact]
        public void RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFeeInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFee
            //Assert.IsType<RemitAddResponseRemitAddRsRemitRecRemitInfoFeeChargeAllocFee>(instance);
        }

        /// <summary>
        /// Test the property 'FeeType'
        /// </summary>
        [Fact]
        public void FeeTypeTest()
        {
            // TODO unit test for the property 'FeeType'
        }

        /// <summary>
        /// Test the property 'CurAmt'
        /// </summary>
        [Fact]
        public void CurAmtTest()
        {
            // TODO unit test for the property 'CurAmt'
        }
    }
}
