/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode
        //private RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode instance;

        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCodeTests()
        {
            // TODO uncomment below to create an instance of RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode
            //instance = new RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode
        /// </summary>
        [Fact]
        public void RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode
            //Assert.IsType<RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode>(instance);
        }

        /// <summary>
        /// Test the property 'CurCodeType'
        /// </summary>
        [Fact]
        public void CurCodeTypeTest()
        {
            // TODO unit test for the property 'CurCodeType'
        }

        /// <summary>
        /// Test the property 'CurCodeValue'
        /// </summary>
        [Fact]
        public void CurCodeValueTest()
        {
            // TODO unit test for the property 'CurCodeValue'
        }
    }
}
