/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail
        //private RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail instance;

        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmailTests()
        {
            // TODO uncomment below to create an instance of RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail
            //instance = new RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail
        /// </summary>
        [Fact]
        public void RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmailInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail
            //Assert.IsType<RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail>(instance);
        }

        /// <summary>
        /// Test the property 'EmailType'
        /// </summary>
        [Fact]
        public void EmailTypeTest()
        {
            // TODO unit test for the property 'EmailType'
        }

        /// <summary>
        /// Test the property 'EmailAddr'
        /// </summary>
        [Fact]
        public void EmailAddrTest()
        {
            // TODO unit test for the property 'EmailAddr'
        }
    }
}
