/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing RemitStatInqRsRemitStatInqRsRemitStatusRec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemitStatInqRsRemitStatInqRsRemitStatusRecTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemitStatInqRsRemitStatInqRsRemitStatusRec
        //private RemitStatInqRsRemitStatInqRsRemitStatusRec instance;

        public RemitStatInqRsRemitStatInqRsRemitStatusRecTests()
        {
            // TODO uncomment below to create an instance of RemitStatInqRsRemitStatInqRsRemitStatusRec
            //instance = new RemitStatInqRsRemitStatInqRsRemitStatusRec();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemitStatInqRsRemitStatInqRsRemitStatusRec
        /// </summary>
        [Fact]
        public void RemitStatInqRsRemitStatInqRsRemitStatusRecInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemitStatInqRsRemitStatInqRsRemitStatusRec
            //Assert.IsType<RemitStatInqRsRemitStatInqRsRemitStatusRec>(instance);
        }

        /// <summary>
        /// Test the property 'RemitStatus'
        /// </summary>
        [Fact]
        public void RemitStatusTest()
        {
            // TODO unit test for the property 'RemitStatus'
        }
    }
}
