/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing ResultStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResultStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResultStatus
        //private ResultStatus instance;

        public ResultStatusTests()
        {
            // TODO uncomment below to create an instance of ResultStatus
            //instance = new ResultStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResultStatus
        /// </summary>
        [Fact]
        public void ResultStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResultStatus
            //Assert.IsType<ResultStatus>(instance);
        }

        /// <summary>
        /// Test the property 'ResultCode'
        /// </summary>
        [Fact]
        public void ResultCodeTest()
        {
            // TODO unit test for the property 'ResultCode'
        }

        /// <summary>
        /// Test the property 'ResultDes'
        /// </summary>
        [Fact]
        public void ResultDesTest()
        {
            // TODO unit test for the property 'ResultDes'
        }

        /// <summary>
        /// Test the property 'ResultTitle'
        /// </summary>
        [Fact]
        public void ResultTitleTest()
        {
            // TODO unit test for the property 'ResultTitle'
        }
    }
}
