/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing ValidateIbanDetailsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidateIbanDetailsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidateIbanDetailsRequest
        //private ValidateIbanDetailsRequest instance;

        public ValidateIbanDetailsRequestTests()
        {
            // TODO uncomment below to create an instance of ValidateIbanDetailsRequest
            //instance = new ValidateIbanDetailsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidateIbanDetailsRequest
        /// </summary>
        [Fact]
        public void ValidateIbanDetailsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidateIbanDetailsRequest
            //Assert.IsType<ValidateIbanDetailsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'RqUID'
        /// </summary>
        [Fact]
        public void RqUIDTest()
        {
            // TODO unit test for the property 'RqUID'
        }

        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Fact]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }

        /// <summary>
        /// Test the property 'ChannelName'
        /// </summary>
        [Fact]
        public void ChannelNameTest()
        {
            // TODO unit test for the property 'ChannelName'
        }

        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }

        /// <summary>
        /// Test the property 'SkipCBDValidation'
        /// </summary>
        [Fact]
        public void SkipCBDValidationTest()
        {
            // TODO unit test for the property 'SkipCBDValidation'
        }

        /// <summary>
        /// Test the property 'SkipCBDdata'
        /// </summary>
        [Fact]
        public void SkipCBDdataTest()
        {
            // TODO unit test for the property 'SkipCBDdata'
        }
    }
}
