/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing ValidateIbanDetailsResponseDataFtBeneficiaries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidateIbanDetailsResponseDataFtBeneficiariesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidateIbanDetailsResponseDataFtBeneficiaries
        //private ValidateIbanDetailsResponseDataFtBeneficiaries instance;

        public ValidateIbanDetailsResponseDataFtBeneficiariesTests()
        {
            // TODO uncomment below to create an instance of ValidateIbanDetailsResponseDataFtBeneficiaries
            //instance = new ValidateIbanDetailsResponseDataFtBeneficiaries();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidateIbanDetailsResponseDataFtBeneficiaries
        /// </summary>
        [Fact]
        public void ValidateIbanDetailsResponseDataFtBeneficiariesInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidateIbanDetailsResponseDataFtBeneficiaries
            //Assert.IsType<ValidateIbanDetailsResponseDataFtBeneficiaries>(instance);
        }

        /// <summary>
        /// Test the property 'RimNo'
        /// </summary>
        [Fact]
        public void RimNoTest()
        {
            // TODO unit test for the property 'RimNo'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }

        /// <summary>
        /// Test the property 'StatusDesc'
        /// </summary>
        [Fact]
        public void StatusDescTest()
        {
            // TODO unit test for the property 'StatusDesc'
        }

        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }

        /// <summary>
        /// Test the property 'NickName'
        /// </summary>
        [Fact]
        public void NickNameTest()
        {
            // TODO unit test for the property 'NickName'
        }

        /// <summary>
        /// Test the property 'BankCity'
        /// </summary>
        [Fact]
        public void BankCityTest()
        {
            // TODO unit test for the property 'BankCity'
        }

        /// <summary>
        /// Test the property 'BranchCity'
        /// </summary>
        [Fact]
        public void BranchCityTest()
        {
            // TODO unit test for the property 'BranchCity'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'BranchName'
        /// </summary>
        [Fact]
        public void BranchNameTest()
        {
            // TODO unit test for the property 'BranchName'
        }

        /// <summary>
        /// Test the property 'BankCountry'
        /// </summary>
        [Fact]
        public void BankCountryTest()
        {
            // TODO unit test for the property 'BankCountry'
        }

        /// <summary>
        /// Test the property 'SwiftCode'
        /// </summary>
        [Fact]
        public void SwiftCodeTest()
        {
            // TODO unit test for the property 'SwiftCode'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }

        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Fact]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }

        /// <summary>
        /// Test the property 'MaskedAccountNumber'
        /// </summary>
        [Fact]
        public void MaskedAccountNumberTest()
        {
            // TODO unit test for the property 'MaskedAccountNumber'
        }

        /// <summary>
        /// Test the property 'BeneficiaryType'
        /// </summary>
        [Fact]
        public void BeneficiaryTypeTest()
        {
            // TODO unit test for the property 'BeneficiaryType'
        }

        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Fact]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }

        /// <summary>
        /// Test the property 'RoutingNo'
        /// </summary>
        [Fact]
        public void RoutingNoTest()
        {
            // TODO unit test for the property 'RoutingNo'
        }

        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Fact]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }

        /// <summary>
        /// Test the property 'BeneficiaryName'
        /// </summary>
        [Fact]
        public void BeneficiaryNameTest()
        {
            // TODO unit test for the property 'BeneficiaryName'
        }

        /// <summary>
        /// Test the property 'Benebankabaetc'
        /// </summary>
        [Fact]
        public void BenebankabaetcTest()
        {
            // TODO unit test for the property 'Benebankabaetc'
        }

        /// <summary>
        /// Test the property 'BenefType'
        /// </summary>
        [Fact]
        public void BenefTypeTest()
        {
            // TODO unit test for the property 'BenefType'
        }

        /// <summary>
        /// Test the property 'IbanName'
        /// </summary>
        [Fact]
        public void IbanNameTest()
        {
            // TODO unit test for the property 'IbanName'
        }
    }
}
