/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRef
        //private XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRef instance;

        public XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRefTests()
        {
            // TODO uncomment below to create an instance of XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRef
            //instance = new XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRef();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRef
        /// </summary>
        [Fact]
        public void XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRefInstanceTest()
        {
            // TODO uncomment below to test "IsType" XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRef
            //Assert.IsType<XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoAcctRef>(instance);
        }

        /// <summary>
        /// Test the property 'AcctKeys'
        /// </summary>
        [Fact]
        public void AcctKeysTest()
        {
            // TODO unit test for the property 'AcctKeys'
        }
    }
}
