/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing XferAddResponseXferAddRsStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XferAddResponseXferAddRsStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XferAddResponseXferAddRsStatus
        //private XferAddResponseXferAddRsStatus instance;

        public XferAddResponseXferAddRsStatusTests()
        {
            // TODO uncomment below to create an instance of XferAddResponseXferAddRsStatus
            //instance = new XferAddResponseXferAddRsStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XferAddResponseXferAddRsStatus
        /// </summary>
        [Fact]
        public void XferAddResponseXferAddRsStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" XferAddResponseXferAddRsStatus
            //Assert.IsType<XferAddResponseXferAddRsStatus>(instance);
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }

        /// <summary>
        /// Test the property 'ServerStatusCode'
        /// </summary>
        [Fact]
        public void ServerStatusCodeTest()
        {
            // TODO unit test for the property 'ServerStatusCode'
        }

        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Fact]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }

        /// <summary>
        /// Test the property 'StatusDesc'
        /// </summary>
        [Fact]
        public void StatusDescTest()
        {
            // TODO unit test for the property 'StatusDesc'
        }

        /// <summary>
        /// Test the property 'AdditionalStatus'
        /// </summary>
        [Fact]
        public void AdditionalStatusTest()
        {
            // TODO unit test for the property 'AdditionalStatus'
        }
    }
}
