/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmtTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmt
        //private XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmt instance;

        public XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmtTests()
        {
            // TODO uncomment below to create an instance of XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmt
            //instance = new XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmt
        /// </summary>
        [Fact]
        public void XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmtInstanceTest()
        {
            // TODO uncomment below to test "IsType" XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmt
            //Assert.IsType<XferAddRequestXferAddRqMsgRqHdrFeeRqHdrDebitRefDebitInfoCompositeCurAmtCurAmt>(instance);
        }

        /// <summary>
        /// Test the property 'Amt'
        /// </summary>
        [Fact]
        public void AmtTest()
        {
            // TODO unit test for the property 'Amt'
        }

        /// <summary>
        /// Test the property 'AcctType'
        /// </summary>
        [Fact]
        public void AcctTypeTest()
        {
            // TODO unit test for the property 'AcctType'
        }

        /// <summary>
        /// Test the property 'CurCode'
        /// </summary>
        [Fact]
        public void CurCodeTest()
        {
            // TODO unit test for the property 'CurCode'
        }
    }
}
