/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing XferAddRequestXferAddRqMsgRqHdrSvcIdent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XferAddRequestXferAddRqMsgRqHdrSvcIdentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XferAddRequestXferAddRqMsgRqHdrSvcIdent
        //private XferAddRequestXferAddRqMsgRqHdrSvcIdent instance;

        public XferAddRequestXferAddRqMsgRqHdrSvcIdentTests()
        {
            // TODO uncomment below to create an instance of XferAddRequestXferAddRqMsgRqHdrSvcIdent
            //instance = new XferAddRequestXferAddRqMsgRqHdrSvcIdent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XferAddRequestXferAddRqMsgRqHdrSvcIdent
        /// </summary>
        [Fact]
        public void XferAddRequestXferAddRqMsgRqHdrSvcIdentInstanceTest()
        {
            // TODO uncomment below to test "IsType" XferAddRequestXferAddRqMsgRqHdrSvcIdent
            //Assert.IsType<XferAddRequestXferAddRqMsgRqHdrSvcIdent>(instance);
        }

        /// <summary>
        /// Test the property 'SvcProviderName'
        /// </summary>
        [Fact]
        public void SvcProviderNameTest()
        {
            // TODO unit test for the property 'SvcProviderName'
        }

        /// <summary>
        /// Test the property 'SvcProviderId'
        /// </summary>
        [Fact]
        public void SvcProviderIdTest()
        {
            // TODO unit test for the property 'SvcProviderId'
        }

        /// <summary>
        /// Test the property 'SvcName'
        /// </summary>
        [Fact]
        public void SvcNameTest()
        {
            // TODO unit test for the property 'SvcName'
        }

        /// <summary>
        /// Test the property 'SvcId'
        /// </summary>
        [Fact]
        public void SvcIdTest()
        {
            // TODO unit test for the property 'SvcId'
        }

        /// <summary>
        /// Test the property 'OriginatorID'
        /// </summary>
        [Fact]
        public void OriginatorIDTest()
        {
            // TODO unit test for the property 'OriginatorID'
        }
    }
}
