/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef
        //private XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef instance;

        public XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRefTests()
        {
            // TODO uncomment below to create an instance of XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef
            //instance = new XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef
        /// </summary>
        [Fact]
        public void XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRefInstanceTest()
        {
            // TODO uncomment below to test "IsType" XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef
            //Assert.IsType<XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef>(instance);
        }

        /// <summary>
        /// Test the property 'ForExQuoteInfo'
        /// </summary>
        [Fact]
        public void ForExQuoteInfoTest()
        {
            // TODO unit test for the property 'ForExQuoteInfo'
        }
    }
}
