/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing XferAddRequestXferAddRqXferInfoForExDealRefForExDealRec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XferAddRequestXferAddRqXferInfoForExDealRefForExDealRecTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XferAddRequestXferAddRqXferInfoForExDealRefForExDealRec
        //private XferAddRequestXferAddRqXferInfoForExDealRefForExDealRec instance;

        public XferAddRequestXferAddRqXferInfoForExDealRefForExDealRecTests()
        {
            // TODO uncomment below to create an instance of XferAddRequestXferAddRqXferInfoForExDealRefForExDealRec
            //instance = new XferAddRequestXferAddRqXferInfoForExDealRefForExDealRec();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XferAddRequestXferAddRqXferInfoForExDealRefForExDealRec
        /// </summary>
        [Fact]
        public void XferAddRequestXferAddRqXferInfoForExDealRefForExDealRecInstanceTest()
        {
            // TODO uncomment below to test "IsType" XferAddRequestXferAddRqXferInfoForExDealRefForExDealRec
            //Assert.IsType<XferAddRequestXferAddRqXferInfoForExDealRefForExDealRec>(instance);
        }

        /// <summary>
        /// Test the property 'ForExDealId'
        /// </summary>
        [Fact]
        public void ForExDealIdTest()
        {
            // TODO unit test for the property 'ForExDealId'
        }

        /// <summary>
        /// Test the property 'CrossRate'
        /// </summary>
        [Fact]
        public void CrossRateTest()
        {
            // TODO unit test for the property 'CrossRate'
        }

        /// <summary>
        /// Test the property 'PayDRInt'
        /// </summary>
        [Fact]
        public void PayDRIntTest()
        {
            // TODO unit test for the property 'PayDRInt'
        }

        /// <summary>
        /// Test the property 'ChrgChkBal'
        /// </summary>
        [Fact]
        public void ChrgChkBalTest()
        {
            // TODO unit test for the property 'ChrgChkBal'
        }
    }
}
