/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing XferAddResponseXferAddRsXferRecXferInfoRefData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XferAddResponseXferAddRsXferRecXferInfoRefDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XferAddResponseXferAddRsXferRecXferInfoRefData
        //private XferAddResponseXferAddRsXferRecXferInfoRefData instance;

        public XferAddResponseXferAddRsXferRecXferInfoRefDataTests()
        {
            // TODO uncomment below to create an instance of XferAddResponseXferAddRsXferRecXferInfoRefData
            //instance = new XferAddResponseXferAddRsXferRecXferInfoRefData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XferAddResponseXferAddRsXferRecXferInfoRefData
        /// </summary>
        [Fact]
        public void XferAddResponseXferAddRsXferRecXferInfoRefDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" XferAddResponseXferAddRsXferRecXferInfoRefData
            //Assert.IsType<XferAddResponseXferAddRsXferRecXferInfoRefData>(instance);
        }

        /// <summary>
        /// Test the property 'RefIdent'
        /// </summary>
        [Fact]
        public void RefIdentTest()
        {
            // TODO unit test for the property 'RefIdent'
        }
    }
}
