/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cbd.MobileExperienceApi.Model;
using Cbd.MobileExperienceApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cbd.MobileExperienceApi.Test.Model
{
    /// <summary>
    ///  Class for testing XferAddResponseXferAddRsXferRec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XferAddResponseXferAddRsXferRecTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XferAddResponseXferAddRsXferRec
        //private XferAddResponseXferAddRsXferRec instance;

        public XferAddResponseXferAddRsXferRecTests()
        {
            // TODO uncomment below to create an instance of XferAddResponseXferAddRsXferRec
            //instance = new XferAddResponseXferAddRsXferRec();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XferAddResponseXferAddRsXferRec
        /// </summary>
        [Fact]
        public void XferAddResponseXferAddRsXferRecInstanceTest()
        {
            // TODO uncomment below to test "IsType" XferAddResponseXferAddRsXferRec
            //Assert.IsType<XferAddResponseXferAddRsXferRec>(instance);
        }

        /// <summary>
        /// Test the property 'XferInfo'
        /// </summary>
        [Fact]
        public void XferInfoTest()
        {
            // TODO unit test for the property 'XferInfo'
        }

        /// <summary>
        /// Test the property 'XferStatusRec'
        /// </summary>
        [Fact]
        public void XferStatusRecTest()
        {
            // TODO unit test for the property 'XferStatusRec'
        }
    }
}
