/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent
    /// </summary>
    [DataContract(Name = "AcctAcctTrnInq_request_AcctAcctTrnInqRq_MsgRqHdr_SvcIdent")]
    public partial class AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent" /> class.
        /// </summary>
        /// <param name="svcProviderName">svcProviderName (required).</param>
        /// <param name="svcProviderId">svcProviderId (required).</param>
        /// <param name="svcName">svcName.</param>
        /// <param name="svcId">svcId.</param>
        public AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent(string svcProviderName = default(string), string svcProviderId = default(string), string svcName = default(string), string svcId = default(string))
        {
            // to ensure "svcProviderName" is required (not null)
            if (svcProviderName == null)
            {
                throw new ArgumentNullException("svcProviderName is a required property for AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent and cannot be null");
            }
            this.SvcProviderName = svcProviderName;
            // to ensure "svcProviderId" is required (not null)
            if (svcProviderId == null)
            {
                throw new ArgumentNullException("svcProviderId is a required property for AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent and cannot be null");
            }
            this.SvcProviderId = svcProviderId;
            this.SvcName = svcName;
            this.SvcId = svcId;
        }

        /// <summary>
        /// Gets or Sets SvcProviderName
        /// </summary>
        [DataMember(Name = "SvcProviderName", IsRequired = true, EmitDefaultValue = true)]
        public string SvcProviderName { get; set; }

        /// <summary>
        /// Gets or Sets SvcProviderId
        /// </summary>
        [DataMember(Name = "SvcProviderId", IsRequired = true, EmitDefaultValue = true)]
        public string SvcProviderId { get; set; }

        /// <summary>
        /// Gets or Sets SvcName
        /// </summary>
        [DataMember(Name = "SvcName", EmitDefaultValue = false)]
        public string SvcName { get; set; }

        /// <summary>
        /// Gets or Sets SvcId
        /// </summary>
        [DataMember(Name = "SvcId", EmitDefaultValue = false)]
        public string SvcId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AcctAcctTrnInqRequestAcctAcctTrnInqRqMsgRqHdrSvcIdent {\n");
            sb.Append("  SvcProviderName: ").Append(SvcProviderName).Append("\n");
            sb.Append("  SvcProviderId: ").Append(SvcProviderId).Append("\n");
            sb.Append("  SvcName: ").Append(SvcName).Append("\n");
            sb.Append("  SvcId: ").Append(SvcId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SvcProviderName (string) maxLength
            if (this.SvcProviderName != null && this.SvcProviderName.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for SvcProviderName, length must be less than 1024.", new [] { "SvcProviderName" });
            }

            // SvcProviderId (string) maxLength
            if (this.SvcProviderId != null && this.SvcProviderId.Length > 36)
            {
                yield return new ValidationResult("Invalid value for SvcProviderId, length must be less than 36.", new [] { "SvcProviderId" });
            }

            // SvcName (string) maxLength
            if (this.SvcName != null && this.SvcName.Length > 32)
            {
                yield return new ValidationResult("Invalid value for SvcName, length must be less than 32.", new [] { "SvcName" });
            }

            // SvcId (string) maxLength
            if (this.SvcId != null && this.SvcId.Length > 36)
            {
                yield return new ValidationResult("Invalid value for SvcId, length must be less than 36.", new [] { "SvcId" });
            }

            yield break;
        }
    }

}
