/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSel
    /// </summary>
    [DataContract(Name = "AcctAcctTrnInq_request_AcctAcctTrnInqRq_AcctTrnSel")]
    public partial class AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSel" /> class.
        /// </summary>
        /// <param name="acctKeys">acctKeys.</param>
        /// <param name="dtRange">dtRange.</param>
        /// <param name="trnRefNo">trnRefNo.</param>
        /// <param name="trnType">trnType.</param>
        /// <param name="partyInfo">partyInfo.</param>
        /// <param name="partyKeys">partyKeys.</param>
        public AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSel(AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelAcctKeys acctKeys = default(AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelAcctKeys), AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange dtRange = default(AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange), string trnRefNo = default(string), AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelTrnType trnType = default(AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelTrnType), AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyInfo partyInfo = default(AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyInfo), AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyKeys partyKeys = default(AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyKeys))
        {
            this.AcctKeys = acctKeys;
            this.DtRange = dtRange;
            this.TrnRefNo = trnRefNo;
            this.TrnType = trnType;
            this.PartyInfo = partyInfo;
            this.PartyKeys = partyKeys;
        }

        /// <summary>
        /// Gets or Sets AcctKeys
        /// </summary>
        [DataMember(Name = "AcctKeys", EmitDefaultValue = false)]
        public AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelAcctKeys AcctKeys { get; set; }

        /// <summary>
        /// Gets or Sets DtRange
        /// </summary>
        [DataMember(Name = "DtRange", EmitDefaultValue = false)]
        public AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelDtRange DtRange { get; set; }

        /// <summary>
        /// Gets or Sets TrnRefNo
        /// </summary>
        [DataMember(Name = "TrnRefNo", EmitDefaultValue = false)]
        public string TrnRefNo { get; set; }

        /// <summary>
        /// Gets or Sets TrnType
        /// </summary>
        [DataMember(Name = "TrnType", EmitDefaultValue = false)]
        public AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelTrnType TrnType { get; set; }

        /// <summary>
        /// Gets or Sets PartyInfo
        /// </summary>
        [DataMember(Name = "PartyInfo", EmitDefaultValue = false)]
        public AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyInfo PartyInfo { get; set; }

        /// <summary>
        /// Gets or Sets PartyKeys
        /// </summary>
        [DataMember(Name = "PartyKeys", EmitDefaultValue = false)]
        public AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyKeys PartyKeys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSel {\n");
            sb.Append("  AcctKeys: ").Append(AcctKeys).Append("\n");
            sb.Append("  DtRange: ").Append(DtRange).Append("\n");
            sb.Append("  TrnRefNo: ").Append(TrnRefNo).Append("\n");
            sb.Append("  TrnType: ").Append(TrnType).Append("\n");
            sb.Append("  PartyInfo: ").Append(PartyInfo).Append("\n");
            sb.Append("  PartyKeys: ").Append(PartyKeys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TrnRefNo (string) maxLength
            if (this.TrnRefNo != null && this.TrnRefNo.Length > 200)
            {
                yield return new ValidationResult("Invalid value for TrnRefNo, length must be less than 200.", new [] { "TrnRefNo" });
            }

            yield break;
        }
    }

}
