/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyInfoIssuedIdentInner
    /// </summary>
    [DataContract(Name = "AcctAcctTrnInq_request_AcctAcctTrnInqRq_AcctTrnSel_PartyInfo_IssuedIdent_inner")]
    public partial class AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyInfoIssuedIdentInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyInfoIssuedIdentInner" /> class.
        /// </summary>
        /// <param name="issuedIdentName">issuedIdentName.</param>
        /// <param name="issuedIdentValue">issuedIdentValue.</param>
        public AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyInfoIssuedIdentInner(string issuedIdentName = default(string), string issuedIdentValue = default(string))
        {
            this.IssuedIdentName = issuedIdentName;
            this.IssuedIdentValue = issuedIdentValue;
        }

        /// <summary>
        /// Gets or Sets IssuedIdentName
        /// </summary>
        [DataMember(Name = "IssuedIdentName", EmitDefaultValue = false)]
        public string IssuedIdentName { get; set; }

        /// <summary>
        /// Gets or Sets IssuedIdentValue
        /// </summary>
        [DataMember(Name = "IssuedIdentValue", EmitDefaultValue = false)]
        public string IssuedIdentValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AcctAcctTrnInqRequestAcctAcctTrnInqRqAcctTrnSelPartyInfoIssuedIdentInner {\n");
            sb.Append("  IssuedIdentName: ").Append(IssuedIdentName).Append("\n");
            sb.Append("  IssuedIdentValue: ").Append(IssuedIdentValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // IssuedIdentName (string) maxLength
            if (this.IssuedIdentName != null && this.IssuedIdentName.Length > 200)
            {
                yield return new ValidationResult("Invalid value for IssuedIdentName, length must be less than 200.", new [] { "IssuedIdentName" });
            }

            // IssuedIdentValue (string) maxLength
            if (this.IssuedIdentValue != null && this.IssuedIdentValue.Length > 200)
            {
                yield return new ValidationResult("Invalid value for IssuedIdentValue, length must be less than 200.", new [] { "IssuedIdentValue" });
            }

            yield break;
        }
    }

}
