/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdrAcctStatus
    /// </summary>
    [DataContract(Name = "AcctAcctTrnInq_response_AcctAcctTrnInqRs_AcctStmtHdr_AcctStatus")]
    public partial class AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdrAcctStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdrAcctStatus" /> class.
        /// </summary>
        /// <param name="acctStatusCode">acctStatusCode.</param>
        /// <param name="statusDesc">statusDesc.</param>
        public AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdrAcctStatus(string acctStatusCode = default(string), string statusDesc = default(string))
        {
            this.AcctStatusCode = acctStatusCode;
            this.StatusDesc = statusDesc;
        }

        /// <summary>
        /// Gets or Sets AcctStatusCode
        /// </summary>
        [DataMember(Name = "AcctStatusCode", EmitDefaultValue = false)]
        public string AcctStatusCode { get; set; }

        /// <summary>
        /// Gets or Sets StatusDesc
        /// </summary>
        [DataMember(Name = "StatusDesc", EmitDefaultValue = false)]
        public string StatusDesc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AcctAcctTrnInqResponseAcctAcctTrnInqRsAcctStmtHdrAcctStatus {\n");
            sb.Append("  AcctStatusCode: ").Append(AcctStatusCode).Append("\n");
            sb.Append("  StatusDesc: ").Append(StatusDesc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
