/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// Data type for Current Account AcctAcctTrnInqRs operation
    /// </summary>
    [DataContract(Name = "AcctAcctTrnInq-response")]
    public partial class AcctAcctTrnInqResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AcctAcctTrnInqResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AcctAcctTrnInqResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AcctAcctTrnInqResponse" /> class.
        /// </summary>
        /// <param name="acctAcctTrnInqRs">acctAcctTrnInqRs (required).</param>
        public AcctAcctTrnInqResponse(AcctAcctTrnInqResponseAcctAcctTrnInqRs acctAcctTrnInqRs = default(AcctAcctTrnInqResponseAcctAcctTrnInqRs))
        {
            // to ensure "acctAcctTrnInqRs" is required (not null)
            if (acctAcctTrnInqRs == null)
            {
                throw new ArgumentNullException("acctAcctTrnInqRs is a required property for AcctAcctTrnInqResponse and cannot be null");
            }
            this.AcctAcctTrnInqRs = acctAcctTrnInqRs;
        }

        /// <summary>
        /// Gets or Sets AcctAcctTrnInqRs
        /// </summary>
        [DataMember(Name = "AcctAcctTrnInqRs", IsRequired = true, EmitDefaultValue = true)]
        public AcctAcctTrnInqResponseAcctAcctTrnInqRs AcctAcctTrnInqRs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AcctAcctTrnInqResponse {\n");
            sb.Append("  AcctAcctTrnInqRs: ").Append(AcctAcctTrnInqRs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
