/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest
    /// </summary>
    [DataContract(Name = "dda_enquirydetails_request_getDDAEnquiryDetails_req_DDAEnquiryRequest")]
    public partial class DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest" /> class.
        /// </summary>
        /// <param name="hEADER">hEADER (required).</param>
        /// <param name="bODY">bODY (required).</param>
        public DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest(DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequestHEADER hEADER = default(DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequestHEADER), DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequestBODY bODY = default(DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequestBODY))
        {
            // to ensure "hEADER" is required (not null)
            if (hEADER == null)
            {
                throw new ArgumentNullException("hEADER is a required property for DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest and cannot be null");
            }
            this.HEADER = hEADER;
            // to ensure "bODY" is required (not null)
            if (bODY == null)
            {
                throw new ArgumentNullException("bODY is a required property for DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest and cannot be null");
            }
            this.BODY = bODY;
        }

        /// <summary>
        /// Gets or Sets HEADER
        /// </summary>
        [DataMember(Name = "HEADER", IsRequired = true, EmitDefaultValue = true)]
        public DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequestHEADER HEADER { get; set; }

        /// <summary>
        /// Gets or Sets BODY
        /// </summary>
        [DataMember(Name = "BODY", IsRequired = true, EmitDefaultValue = true)]
        public DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequestBODY BODY { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DdaEnquirydetailsRequestGetDDAEnquiryDetailsReqDDAEnquiryRequest {\n");
            sb.Append("  HEADER: ").Append(HEADER).Append("\n");
            sb.Append("  BODY: ").Append(BODY).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
