/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// DdaEnquirydetailsRequestGetDDAEnquiryDetails
    /// </summary>
    [DataContract(Name = "dda_enquirydetails_request_getDDAEnquiryDetails")]
    public partial class DdaEnquirydetailsRequestGetDDAEnquiryDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DdaEnquirydetailsRequestGetDDAEnquiryDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DdaEnquirydetailsRequestGetDDAEnquiryDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DdaEnquirydetailsRequestGetDDAEnquiryDetails" /> class.
        /// </summary>
        /// <param name="rqUID">rqUID (required).</param>
        /// <param name="req">req (required).</param>
        /// <param name="iChannelId">iChannelId.</param>
        /// <param name="iUserId">iUserId.</param>
        /// <param name="iFuncId">iFuncId.</param>
        public DdaEnquirydetailsRequestGetDDAEnquiryDetails(string rqUID = default(string), DdaEnquirydetailsRequestGetDDAEnquiryDetailsReq req = default(DdaEnquirydetailsRequestGetDDAEnquiryDetailsReq), Object iChannelId = default(Object), Object iUserId = default(Object), Object iFuncId = default(Object))
        {
            // to ensure "rqUID" is required (not null)
            if (rqUID == null)
            {
                throw new ArgumentNullException("rqUID is a required property for DdaEnquirydetailsRequestGetDDAEnquiryDetails and cannot be null");
            }
            this.RqUID = rqUID;
            // to ensure "req" is required (not null)
            if (req == null)
            {
                throw new ArgumentNullException("req is a required property for DdaEnquirydetailsRequestGetDDAEnquiryDetails and cannot be null");
            }
            this.Req = req;
            this.IChannelId = iChannelId;
            this.IUserId = iUserId;
            this.IFuncId = iFuncId;
        }

        /// <summary>
        /// Gets or Sets RqUID
        /// </summary>
        [DataMember(Name = "RqUID", IsRequired = true, EmitDefaultValue = true)]
        public string RqUID { get; set; }

        /// <summary>
        /// Gets or Sets Req
        /// </summary>
        [DataMember(Name = "req", IsRequired = true, EmitDefaultValue = true)]
        public DdaEnquirydetailsRequestGetDDAEnquiryDetailsReq Req { get; set; }

        /// <summary>
        /// Gets or Sets IChannelId
        /// </summary>
        [DataMember(Name = "iChannelId", EmitDefaultValue = false)]
        public Object IChannelId { get; set; }

        /// <summary>
        /// Gets or Sets IUserId
        /// </summary>
        [DataMember(Name = "iUserId", EmitDefaultValue = false)]
        public Object IUserId { get; set; }

        /// <summary>
        /// Gets or Sets IFuncId
        /// </summary>
        [DataMember(Name = "iFuncId", EmitDefaultValue = false)]
        public Object IFuncId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DdaEnquirydetailsRequestGetDDAEnquiryDetails {\n");
            sb.Append("  RqUID: ").Append(RqUID).Append("\n");
            sb.Append("  Req: ").Append(Req).Append("\n");
            sb.Append("  IChannelId: ").Append(IChannelId).Append("\n");
            sb.Append("  IUserId: ").Append(IUserId).Append("\n");
            sb.Append("  IFuncId: ").Append(IFuncId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.RqUID != null) {
                // RqUID (string) pattern
                Regex regexRqUID = new Regex(@"^([0-9]|[a-f]|[A-F]){8}(-([0-9]|[a-f]|[A-F]){4})(-([0-9]|[a-f]|[A-F]){4})(-([0-9]|[a-f]|[A-F]){4})(-([0-9]|[a-f]|[A-F]){12})$", RegexOptions.CultureInvariant);
                if (!regexRqUID.Match(this.RqUID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RqUID, must match a pattern of " + regexRqUID, new [] { "RqUID" });
                }
            }

            yield break;
        }
    }

}
