/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// ErrorObject2Result
    /// </summary>
    [DataContract(Name = "error_object_2_result")]
    public partial class ErrorObject2Result : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorObject2Result" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ErrorObject2Result() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorObject2Result" /> class.
        /// </summary>
        /// <param name="eRRORCODEID">General error Id encountered on the API (required).</param>
        /// <param name="eRRORDESCRIPTION">A description of the error in a human-readable format. Could be http reason (required).</param>
        /// <param name="rows">An array containing all of the errors that occurred (required).</param>
        public ErrorObject2Result(string eRRORCODEID = default(string), string eRRORDESCRIPTION = default(string), List<Object> rows = default(List<Object>))
        {
            // to ensure "eRRORCODEID" is required (not null)
            if (eRRORCODEID == null)
            {
                throw new ArgumentNullException("eRRORCODEID is a required property for ErrorObject2Result and cannot be null");
            }
            this.ERROR_CODE_ID = eRRORCODEID;
            // to ensure "eRRORDESCRIPTION" is required (not null)
            if (eRRORDESCRIPTION == null)
            {
                throw new ArgumentNullException("eRRORDESCRIPTION is a required property for ErrorObject2Result and cannot be null");
            }
            this.ERROR_DESCRIPTION = eRRORDESCRIPTION;
            // to ensure "rows" is required (not null)
            if (rows == null)
            {
                throw new ArgumentNullException("rows is a required property for ErrorObject2Result and cannot be null");
            }
            this.Rows = rows;
        }

        /// <summary>
        /// General error Id encountered on the API
        /// </summary>
        /// <value>General error Id encountered on the API</value>
        [DataMember(Name = "ERROR_CODE_ID", IsRequired = true, EmitDefaultValue = true)]
        public string ERROR_CODE_ID { get; set; }

        /// <summary>
        /// A description of the error in a human-readable format. Could be http reason
        /// </summary>
        /// <value>A description of the error in a human-readable format. Could be http reason</value>
        [DataMember(Name = "ERROR_DESCRIPTION", IsRequired = true, EmitDefaultValue = true)]
        public string ERROR_DESCRIPTION { get; set; }

        /// <summary>
        /// An array containing all of the errors that occurred
        /// </summary>
        /// <value>An array containing all of the errors that occurred</value>
        [DataMember(Name = "Rows", IsRequired = true, EmitDefaultValue = true)]
        public List<Object> Rows { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ErrorObject2Result {\n");
            sb.Append("  ERROR_CODE_ID: ").Append(ERROR_CODE_ID).Append("\n");
            sb.Append("  ERROR_DESCRIPTION: ").Append(ERROR_DESCRIPTION).Append("\n");
            sb.Append("  Rows: ").Append(Rows).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
