/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// ErrorObjectAcctAcctTrnInqRsStatusAdditionalStatus
    /// </summary>
    [DataContract(Name = "error_object_AcctAcctTrnInqRs_Status_AdditionalStatus")]
    public partial class ErrorObjectAcctAcctTrnInqRsStatusAdditionalStatus : IValidatableObject
    {
        /// <summary>
        /// Defines Severity
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SeverityEnum
        {
            /// <summary>
            /// Enum Error for value: Error
            /// </summary>
            [EnumMember(Value = "Error")]
            Error = 1,

            /// <summary>
            /// Enum Warning for value: Warning
            /// </summary>
            [EnumMember(Value = "Warning")]
            Warning = 2,

            /// <summary>
            /// Enum Info for value: Info
            /// </summary>
            [EnumMember(Value = "Info")]
            Info = 3
        }


        /// <summary>
        /// Gets or Sets Severity
        /// </summary>
        [DataMember(Name = "Severity", IsRequired = true, EmitDefaultValue = true)]
        public SeverityEnum Severity { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorObjectAcctAcctTrnInqRsStatusAdditionalStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ErrorObjectAcctAcctTrnInqRsStatusAdditionalStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorObjectAcctAcctTrnInqRsStatusAdditionalStatus" /> class.
        /// </summary>
        /// <param name="statusCode">statusCode (required).</param>
        /// <param name="serverStatusCode">serverStatusCode.</param>
        /// <param name="severity">severity (required).</param>
        /// <param name="statusDesc">statusDesc (required).</param>
        public ErrorObjectAcctAcctTrnInqRsStatusAdditionalStatus(decimal statusCode = default(decimal), string serverStatusCode = default(string), SeverityEnum severity = default(SeverityEnum), string statusDesc = default(string))
        {
            this.StatusCode = statusCode;
            this.Severity = severity;
            // to ensure "statusDesc" is required (not null)
            if (statusDesc == null)
            {
                throw new ArgumentNullException("statusDesc is a required property for ErrorObjectAcctAcctTrnInqRsStatusAdditionalStatus and cannot be null");
            }
            this.StatusDesc = statusDesc;
            this.ServerStatusCode = serverStatusCode;
        }

        /// <summary>
        /// Gets or Sets StatusCode
        /// </summary>
        [DataMember(Name = "StatusCode", IsRequired = true, EmitDefaultValue = true)]
        public decimal StatusCode { get; set; }

        /// <summary>
        /// Gets or Sets ServerStatusCode
        /// </summary>
        [DataMember(Name = "ServerStatusCode", EmitDefaultValue = false)]
        public string ServerStatusCode { get; set; }

        /// <summary>
        /// Gets or Sets StatusDesc
        /// </summary>
        [DataMember(Name = "StatusDesc", IsRequired = true, EmitDefaultValue = true)]
        public string StatusDesc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ErrorObjectAcctAcctTrnInqRsStatusAdditionalStatus {\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  ServerStatusCode: ").Append(ServerStatusCode).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  StatusDesc: ").Append(StatusDesc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // StatusDesc (string) maxLength
            if (this.StatusDesc != null && this.StatusDesc.Length > 255)
            {
                yield return new ValidationResult("Invalid value for StatusDesc, length must be less than 255.", new [] { "StatusDesc" });
            }

            yield break;
        }
    }

}
