/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// PartyinqrsSegmentationType
    /// </summary>
    [DataContract(Name = "partyinqrs_Segmentation_Type")]
    public partial class PartyinqrsSegmentationType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyinqrsSegmentationType" /> class.
        /// </summary>
        /// <param name="segmentCode">segmentCode.</param>
        /// <param name="segmentDesc">segmentDesc.</param>
        public PartyinqrsSegmentationType(string segmentCode = default(string), string segmentDesc = default(string))
        {
            this.SegmentCode = segmentCode;
            this.SegmentDesc = segmentDesc;
        }

        /// <summary>
        /// Gets or Sets SegmentCode
        /// </summary>
        [DataMember(Name = "SegmentCode", EmitDefaultValue = false)]
        public string SegmentCode { get; set; }

        /// <summary>
        /// Gets or Sets SegmentDesc
        /// </summary>
        [DataMember(Name = "SegmentDesc", EmitDefaultValue = false)]
        public string SegmentDesc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartyinqrsSegmentationType {\n");
            sb.Append("  SegmentCode: ").Append(SegmentCode).Append("\n");
            sb.Append("  SegmentDesc: ").Append(SegmentDesc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
