/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// PartyinqrsPartyInqRs
    /// </summary>
    [DataContract(Name = "partyinqrs_PartyInqRs")]
    public partial class PartyinqrsPartyInqRs : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyinqrsPartyInqRs" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PartyinqrsPartyInqRs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyinqrsPartyInqRs" /> class.
        /// </summary>
        /// <param name="status">status (required).</param>
        /// <param name="rqUID">rqUID (required).</param>
        /// <param name="partyRec">partyRec.</param>
        /// <param name="orgPartyRec">orgPartyRec.</param>
        public PartyinqrsPartyInqRs(PartyinqrsStatusType status = default(PartyinqrsStatusType), string rqUID = default(string), PartyinqrsPartyRecType partyRec = default(PartyinqrsPartyRecType), List<PartyinqrsPartyRecType> orgPartyRec = default(List<PartyinqrsPartyRecType>))
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for PartyinqrsPartyInqRs and cannot be null");
            }
            this.Status = status;
            // to ensure "rqUID" is required (not null)
            if (rqUID == null)
            {
                throw new ArgumentNullException("rqUID is a required property for PartyinqrsPartyInqRs and cannot be null");
            }
            this.RqUID = rqUID;
            this.PartyRec = partyRec;
            this.OrgPartyRec = orgPartyRec;
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "Status", IsRequired = true, EmitDefaultValue = true)]
        public PartyinqrsStatusType Status { get; set; }

        /// <summary>
        /// Gets or Sets RqUID
        /// </summary>
        [DataMember(Name = "RqUID", IsRequired = true, EmitDefaultValue = true)]
        public string RqUID { get; set; }

        /// <summary>
        /// Gets or Sets PartyRec
        /// </summary>
        [DataMember(Name = "PartyRec", EmitDefaultValue = false)]
        public PartyinqrsPartyRecType PartyRec { get; set; }

        /// <summary>
        /// Gets or Sets OrgPartyRec
        /// </summary>
        [DataMember(Name = "OrgPartyRec", EmitDefaultValue = false)]
        public List<PartyinqrsPartyRecType> OrgPartyRec { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartyinqrsPartyInqRs {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RqUID: ").Append(RqUID).Append("\n");
            sb.Append("  PartyRec: ").Append(PartyRec).Append("\n");
            sb.Append("  OrgPartyRec: ").Append(OrgPartyRec).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.RqUID != null) {
                // RqUID (string) pattern
                Regex regexRqUID = new Regex(@"^([0-9]|[a-f]|[A-F]){8}(-([0-9]|[a-f]|[A-F]){4})(-([0-9]|[a-f]|[A-F]){4})(-([0-9]|[a-f]|[A-F]){4})(-([0-9]|[a-f]|[A-F]){12})$", RegexOptions.CultureInvariant);
                if (!regexRqUID.Match(this.RqUID).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RqUID, must match a pattern of " + regexRqUID, new [] { "RqUID" });
                }
            }

            yield break;
        }
    }

}
