/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// PartacctrelrsPhoneType
    /// </summary>
    [DataContract(Name = "partacctrelrs_Phone_Type")]
    public partial class PartacctrelrsPhoneType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartacctrelrsPhoneType" /> class.
        /// </summary>
        /// <param name="phoneType">phoneType.</param>
        /// <param name="phoneNum">phoneNum.</param>
        public PartacctrelrsPhoneType(string phoneType = default(string), string phoneNum = default(string))
        {
            this.PhoneType = phoneType;
            this.PhoneNum = phoneNum;
        }

        /// <summary>
        /// Gets or Sets PhoneType
        /// </summary>
        [DataMember(Name = "PhoneType", EmitDefaultValue = false)]
        public string PhoneType { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNum
        /// </summary>
        [DataMember(Name = "PhoneNum", EmitDefaultValue = false)]
        public string PhoneNum { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartacctrelrsPhoneType {\n");
            sb.Append("  PhoneType: ").Append(PhoneType).Append("\n");
            sb.Append("  PhoneNum: ").Append(PhoneNum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
