/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// PartyinqrsPartyRecType
    /// </summary>
    [DataContract(Name = "partyinqrs_PartyRec_Type")]
    public partial class PartyinqrsPartyRecType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyinqrsPartyRecType" /> class.
        /// </summary>
        /// <param name="partyId">partyId.</param>
        /// <param name="partyInfo">partyInfo.</param>
        /// <param name="groupKeys">groupKeys.</param>
        public PartyinqrsPartyRecType(string partyId = default(string), PartyinqrsPartyInfoType partyInfo = default(PartyinqrsPartyInfoType), PartyinqrsGroupKeysType groupKeys = default(PartyinqrsGroupKeysType))
        {
            this.PartyId = partyId;
            this.PartyInfo = partyInfo;
            this.GroupKeys = groupKeys;
        }

        /// <summary>
        /// Gets or Sets PartyId
        /// </summary>
        [DataMember(Name = "PartyId", EmitDefaultValue = false)]
        public string PartyId { get; set; }

        /// <summary>
        /// Gets or Sets PartyInfo
        /// </summary>
        [DataMember(Name = "PartyInfo", EmitDefaultValue = false)]
        public PartyinqrsPartyInfoType PartyInfo { get; set; }

        /// <summary>
        /// Gets or Sets GroupKeys
        /// </summary>
        [DataMember(Name = "GroupKeys", EmitDefaultValue = false)]
        public PartyinqrsGroupKeysType GroupKeys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartyinqrsPartyRecType {\n");
            sb.Append("  PartyId: ").Append(PartyId).Append("\n");
            sb.Append("  PartyInfo: ").Append(PartyInfo).Append("\n");
            sb.Append("  GroupKeys: ").Append(GroupKeys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
