/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// PartyAcctRelInqRequest
    /// </summary>
    [DataContract(Name = "partyAcctRelInq-request")]
    public partial class PartyAcctRelInqRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyAcctRelInqRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PartyAcctRelInqRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyAcctRelInqRequest" /> class.
        /// </summary>
        /// <param name="partyAcctRelInqRq">partyAcctRelInqRq (required).</param>
        public PartyAcctRelInqRequest(Object partyAcctRelInqRq = default(Object))
        {
            // to ensure "partyAcctRelInqRq" is required (not null)
            if (partyAcctRelInqRq == null)
            {
                throw new ArgumentNullException("partyAcctRelInqRq is a required property for PartyAcctRelInqRequest and cannot be null");
            }
            this.PartyAcctRelInqRq = partyAcctRelInqRq;
        }

        /// <summary>
        /// Gets or Sets PartyAcctRelInqRq
        /// </summary>
        [DataMember(Name = "PartyAcctRelInqRq", IsRequired = true, EmitDefaultValue = true)]
        public Object PartyAcctRelInqRq { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartyAcctRelInqRequest {\n");
            sb.Append("  PartyAcctRelInqRq: ").Append(PartyAcctRelInqRq).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
