/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// PartacctrelrsCurCodeType
    /// </summary>
    [DataContract(Name = "partacctrelrs_CurCode_Type")]
    public partial class PartacctrelrsCurCodeType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartacctrelrsCurCodeType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PartacctrelrsCurCodeType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PartacctrelrsCurCodeType" /> class.
        /// </summary>
        /// <param name="curCodeValue">curCodeValue (required).</param>
        /// <param name="curCodeType">curCodeType.</param>
        public PartacctrelrsCurCodeType(string curCodeValue = default(string), string curCodeType = default(string))
        {
            // to ensure "curCodeValue" is required (not null)
            if (curCodeValue == null)
            {
                throw new ArgumentNullException("curCodeValue is a required property for PartacctrelrsCurCodeType and cannot be null");
            }
            this.CurCodeValue = curCodeValue;
            this.CurCodeType = curCodeType;
        }

        /// <summary>
        /// Gets or Sets CurCodeValue
        /// </summary>
        [DataMember(Name = "CurCodeValue", IsRequired = true, EmitDefaultValue = true)]
        public string CurCodeValue { get; set; }

        /// <summary>
        /// Gets or Sets CurCodeType
        /// </summary>
        [DataMember(Name = "CurCodeType", EmitDefaultValue = false)]
        public string CurCodeType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartacctrelrsCurCodeType {\n");
            sb.Append("  CurCodeValue: ").Append(CurCodeValue).Append("\n");
            sb.Append("  CurCodeType: ").Append(CurCodeType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
