/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// PartacctrelrsSegmentationType
    /// </summary>
    [DataContract(Name = "partacctrelrs_Segmentation_Type")]
    public partial class PartacctrelrsSegmentationType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartacctrelrsSegmentationType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PartacctrelrsSegmentationType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PartacctrelrsSegmentationType" /> class.
        /// </summary>
        /// <param name="segmentCode">segmentCode (required).</param>
        /// <param name="segmentDesc">segmentDesc (required).</param>
        /// <param name="chargeSegmentId">chargeSegmentId.</param>
        public PartacctrelrsSegmentationType(string segmentCode = default(string), string segmentDesc = default(string), string chargeSegmentId = default(string))
        {
            // to ensure "segmentCode" is required (not null)
            if (segmentCode == null)
            {
                throw new ArgumentNullException("segmentCode is a required property for PartacctrelrsSegmentationType and cannot be null");
            }
            this.SegmentCode = segmentCode;
            // to ensure "segmentDesc" is required (not null)
            if (segmentDesc == null)
            {
                throw new ArgumentNullException("segmentDesc is a required property for PartacctrelrsSegmentationType and cannot be null");
            }
            this.SegmentDesc = segmentDesc;
            this.ChargeSegmentId = chargeSegmentId;
        }

        /// <summary>
        /// Gets or Sets SegmentCode
        /// </summary>
        [DataMember(Name = "SegmentCode", IsRequired = true, EmitDefaultValue = true)]
        public string SegmentCode { get; set; }

        /// <summary>
        /// Gets or Sets SegmentDesc
        /// </summary>
        [DataMember(Name = "SegmentDesc", IsRequired = true, EmitDefaultValue = true)]
        public string SegmentDesc { get; set; }

        /// <summary>
        /// Gets or Sets ChargeSegmentId
        /// </summary>
        [DataMember(Name = "ChargeSegmentId", EmitDefaultValue = false)]
        public string ChargeSegmentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartacctrelrsSegmentationType {\n");
            sb.Append("  SegmentCode: ").Append(SegmentCode).Append("\n");
            sb.Append("  SegmentDesc: ").Append(SegmentDesc).Append("\n");
            sb.Append("  ChargeSegmentId: ").Append(ChargeSegmentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
