/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// PartyinqrsFatcaDetailsType
    /// </summary>
    [DataContract(Name = "partyinqrs_FatcaDetails_Type")]
    public partial class PartyinqrsFatcaDetailsType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyinqrsFatcaDetailsType" /> class.
        /// </summary>
        /// <param name="tIN">tIN.</param>
        /// <param name="sSN">sSN.</param>
        /// <param name="uSResidentStatus">uSResidentStatus.</param>
        public PartyinqrsFatcaDetailsType(string tIN = default(string), string sSN = default(string), string uSResidentStatus = default(string))
        {
            this.TIN = tIN;
            this.SSN = sSN;
            this.USResidentStatus = uSResidentStatus;
        }

        /// <summary>
        /// Gets or Sets TIN
        /// </summary>
        [DataMember(Name = "TIN", EmitDefaultValue = false)]
        public string TIN { get; set; }

        /// <summary>
        /// Gets or Sets SSN
        /// </summary>
        [DataMember(Name = "SSN", EmitDefaultValue = false)]
        public string SSN { get; set; }

        /// <summary>
        /// Gets or Sets USResidentStatus
        /// </summary>
        [DataMember(Name = "USResidentStatus", EmitDefaultValue = false)]
        public string USResidentStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartyinqrsFatcaDetailsType {\n");
            sb.Append("  TIN: ").Append(TIN).Append("\n");
            sb.Append("  SSN: ").Append(SSN).Append("\n");
            sb.Append("  USResidentStatus: ").Append(USResidentStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
