/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode
    /// </summary>
    [DataContract(Name = "RemitAdd_request_RemitAddRq_RemitInfo_PmtInstruction_FromAcctRef_AcctKeys_CurCode")]
    public partial class RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode" /> class.
        /// </summary>
        /// <param name="curCodeType">curCodeType (required).</param>
        /// <param name="curCodeValue">curCodeValue (required).</param>
        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode(Object curCodeType = default(Object), Object curCodeValue = default(Object))
        {
            // to ensure "curCodeType" is required (not null)
            if (curCodeType == null)
            {
                throw new ArgumentNullException("curCodeType is a required property for RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode and cannot be null");
            }
            this.CurCodeType = curCodeType;
            // to ensure "curCodeValue" is required (not null)
            if (curCodeValue == null)
            {
                throw new ArgumentNullException("curCodeValue is a required property for RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode and cannot be null");
            }
            this.CurCodeValue = curCodeValue;
        }

        /// <summary>
        /// Gets or Sets CurCodeType
        /// </summary>
        [DataMember(Name = "CurCodeType", IsRequired = true, EmitDefaultValue = true)]
        public Object CurCodeType { get; set; }

        /// <summary>
        /// Gets or Sets CurCodeValue
        /// </summary>
        [DataMember(Name = "CurCodeValue", IsRequired = true, EmitDefaultValue = true)]
        public Object CurCodeValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode {\n");
            sb.Append("  CurCodeType: ").Append(CurCodeType).Append("\n");
            sb.Append("  CurCodeValue: ").Append(CurCodeValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
