/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// RemitAddResponseRemitAddRsRemitRecRemitInfoForExDealRefForExDealInfoForExQuoteRef
    /// </summary>
    [DataContract(Name = "RemitAdd_response_RemitAddRs_RemitRec_RemitInfo_ForExDealRef_ForExDealInfo_ForExQuoteRef")]
    public partial class RemitAddResponseRemitAddRsRemitRecRemitInfoForExDealRefForExDealInfoForExQuoteRef : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddResponseRemitAddRsRemitRecRemitInfoForExDealRefForExDealInfoForExQuoteRef" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemitAddResponseRemitAddRsRemitRecRemitInfoForExDealRefForExDealInfoForExQuoteRef() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddResponseRemitAddRsRemitRecRemitInfoForExDealRefForExDealInfoForExQuoteRef" /> class.
        /// </summary>
        /// <param name="crossRate">crossRate (required).</param>
        public RemitAddResponseRemitAddRsRemitRecRemitInfoForExDealRefForExDealInfoForExQuoteRef(string crossRate = default(string))
        {
            // to ensure "crossRate" is required (not null)
            if (crossRate == null)
            {
                throw new ArgumentNullException("crossRate is a required property for RemitAddResponseRemitAddRsRemitRecRemitInfoForExDealRefForExDealInfoForExQuoteRef and cannot be null");
            }
            this.CrossRate = crossRate;
        }

        /// <summary>
        /// Gets or Sets CrossRate
        /// </summary>
        [DataMember(Name = "CrossRate", IsRequired = true, EmitDefaultValue = true)]
        public string CrossRate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemitAddResponseRemitAddRsRemitRecRemitInfoForExDealRefForExDealInfoForExQuoteRef {\n");
            sb.Append("  CrossRate: ").Append(CrossRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CrossRate (string) maxLength
            if (this.CrossRate != null && this.CrossRate.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for CrossRate, length must be less than 1024.", new [] { "CrossRate" });
            }

            yield break;
        }
    }

}
