/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// RemitAddRequestRemitAddRqRemitInfoRemitReceiverBankRef
    /// </summary>
    [DataContract(Name = "RemitAdd_request_RemitAddRq_RemitInfo_RemitReceiverBankRef")]
    public partial class RemitAddRequestRemitAddRqRemitInfoRemitReceiverBankRef : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddRequestRemitAddRqRemitInfoRemitReceiverBankRef" /> class.
        /// </summary>
        /// <param name="receiverBankName">receiverBankName.</param>
        /// <param name="receiverBankSwift">receiverBankSwift.</param>
        /// <param name="receiverBankAddressLine1">receiverBankAddressLine1.</param>
        /// <param name="receiverBankAddressLine2">receiverBankAddressLine2.</param>
        /// <param name="receiverBankAddressLine3">receiverBankAddressLine3.</param>
        /// <param name="receiverBankCodeType">receiverBankCodeType.</param>
        public RemitAddRequestRemitAddRqRemitInfoRemitReceiverBankRef(Object receiverBankName = default(Object), Object receiverBankSwift = default(Object), Object receiverBankAddressLine1 = default(Object), Object receiverBankAddressLine2 = default(Object), Object receiverBankAddressLine3 = default(Object), Object receiverBankCodeType = default(Object))
        {
            this.ReceiverBankName = receiverBankName;
            this.ReceiverBankSwift = receiverBankSwift;
            this.ReceiverBankAddressLine1 = receiverBankAddressLine1;
            this.ReceiverBankAddressLine2 = receiverBankAddressLine2;
            this.ReceiverBankAddressLine3 = receiverBankAddressLine3;
            this.ReceiverBankCodeType = receiverBankCodeType;
        }

        /// <summary>
        /// Gets or Sets ReceiverBankName
        /// </summary>
        [DataMember(Name = "ReceiverBankName", EmitDefaultValue = false)]
        public Object ReceiverBankName { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverBankSwift
        /// </summary>
        [DataMember(Name = "ReceiverBankSwift", EmitDefaultValue = false)]
        public Object ReceiverBankSwift { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverBankAddressLine1
        /// </summary>
        [DataMember(Name = "ReceiverBankAddressLine1", EmitDefaultValue = false)]
        public Object ReceiverBankAddressLine1 { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverBankAddressLine2
        /// </summary>
        [DataMember(Name = "ReceiverBankAddressLine2", EmitDefaultValue = false)]
        public Object ReceiverBankAddressLine2 { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverBankAddressLine3
        /// </summary>
        [DataMember(Name = "ReceiverBankAddressLine3", EmitDefaultValue = false)]
        public Object ReceiverBankAddressLine3 { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverBankCodeType
        /// </summary>
        [DataMember(Name = "ReceiverBankCodeType", EmitDefaultValue = false)]
        public Object ReceiverBankCodeType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemitAddRequestRemitAddRqRemitInfoRemitReceiverBankRef {\n");
            sb.Append("  ReceiverBankName: ").Append(ReceiverBankName).Append("\n");
            sb.Append("  ReceiverBankSwift: ").Append(ReceiverBankSwift).Append("\n");
            sb.Append("  ReceiverBankAddressLine1: ").Append(ReceiverBankAddressLine1).Append("\n");
            sb.Append("  ReceiverBankAddressLine2: ").Append(ReceiverBankAddressLine2).Append("\n");
            sb.Append("  ReceiverBankAddressLine3: ").Append(ReceiverBankAddressLine3).Append("\n");
            sb.Append("  ReceiverBankCodeType: ").Append(ReceiverBankCodeType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
