/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocFeeInnerCurAmt
    /// </summary>
    [DataContract(Name = "RemitAdd_request_RemitAddRq_RemitInfo_PmtInstruction_FeeChargeAlloc_Fee_inner_CurAmt")]
    public partial class RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocFeeInnerCurAmt : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocFeeInnerCurAmt" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocFeeInnerCurAmt() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocFeeInnerCurAmt" /> class.
        /// </summary>
        /// <param name="amt">amt (required).</param>
        /// <param name="curCode">curCode.</param>
        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocFeeInnerCurAmt(double amt = default(double), RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode curCode = default(RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode))
        {
            this.Amt = amt;
            this.CurCode = curCode;
        }

        /// <summary>
        /// Gets or Sets Amt
        /// </summary>
        [DataMember(Name = "Amt", IsRequired = true, EmitDefaultValue = true)]
        public double Amt { get; set; }

        /// <summary>
        /// Gets or Sets CurCode
        /// </summary>
        [DataMember(Name = "CurCode", EmitDefaultValue = false)]
        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionFromAcctRefAcctKeysCurCode CurCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemitAddRequestRemitAddRqRemitInfoPmtInstructionFeeChargeAllocFeeInnerCurAmt {\n");
            sb.Append("  Amt: ").Append(Amt).Append("\n");
            sb.Append("  CurCode: ").Append(CurCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Amt (double) minimum
            if (this.Amt < (double)0)
            {
                yield return new ValidationResult("Invalid value for Amt, must be a value greater than or equal to 0.", new [] { "Amt" });
            }

            yield break;
        }
    }

}
