/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// RemitAddRequestRemitAddRqRemitInfoForExDealRef
    /// </summary>
    [DataContract(Name = "RemitAdd_request_RemitAddRq_RemitInfo_ForExDealRef")]
    public partial class RemitAddRequestRemitAddRqRemitInfoForExDealRef : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddRequestRemitAddRqRemitInfoForExDealRef" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemitAddRequestRemitAddRqRemitInfoForExDealRef() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddRequestRemitAddRqRemitInfoForExDealRef" /> class.
        /// </summary>
        /// <param name="forExDealInfo">forExDealInfo (required).</param>
        public RemitAddRequestRemitAddRqRemitInfoForExDealRef(RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo forExDealInfo = default(RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo))
        {
            // to ensure "forExDealInfo" is required (not null)
            if (forExDealInfo == null)
            {
                throw new ArgumentNullException("forExDealInfo is a required property for RemitAddRequestRemitAddRqRemitInfoForExDealRef and cannot be null");
            }
            this.ForExDealInfo = forExDealInfo;
        }

        /// <summary>
        /// Gets or Sets ForExDealInfo
        /// </summary>
        [DataMember(Name = "ForExDealInfo", IsRequired = true, EmitDefaultValue = true)]
        public RemitAddRequestRemitAddRqRemitInfoForExDealRefForExDealInfo ForExDealInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemitAddRequestRemitAddRqRemitInfoForExDealRef {\n");
            sb.Append("  ForExDealInfo: ").Append(ForExDealInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
