/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocator
    /// </summary>
    [DataContract(Name = "RemitAdd_request_RemitAddRq_RemitInfo_PmtInstruction_PartyInfo_PersonData_Contact_Locator")]
    public partial class RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocator : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocator" /> class.
        /// </summary>
        /// <param name="postAddr">postAddr.</param>
        /// <param name="phoneNum">phoneNum.</param>
        /// <param name="email">email.</param>
        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocator(RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorPostAddr postAddr = default(RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorPostAddr), RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorPhoneNum phoneNum = default(RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorPhoneNum), RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail email = default(RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail))
        {
            this.PostAddr = postAddr;
            this.PhoneNum = phoneNum;
            this.Email = email;
        }

        /// <summary>
        /// Gets or Sets PostAddr
        /// </summary>
        [DataMember(Name = "PostAddr", EmitDefaultValue = false)]
        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorPostAddr PostAddr { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNum
        /// </summary>
        [DataMember(Name = "PhoneNum", EmitDefaultValue = false)]
        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorPhoneNum PhoneNum { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "Email", EmitDefaultValue = false)]
        public RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocatorEmail Email { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemitAddRequestRemitAddRqRemitInfoPmtInstructionPartyInfoPersonDataContactLocator {\n");
            sb.Append("  PostAddr: ").Append(PostAddr).Append("\n");
            sb.Append("  PhoneNum: ").Append(PhoneNum).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
