/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// Type18GenericAPIExecuteServicRsResult
    /// </summary>
    [DataContract(Name = "type_18_GenericAPIExecuteServicRs_Result")]
    public partial class Type18GenericAPIExecuteServicRsResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Type18GenericAPIExecuteServicRsResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Type18GenericAPIExecuteServicRsResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Type18GenericAPIExecuteServicRsResult" /> class.
        /// </summary>
        /// <param name="odataContext">odataContext (required).</param>
        /// <param name="responseJson">responseJson (required).</param>
        public Type18GenericAPIExecuteServicRsResult(string odataContext = default(string), string responseJson = default(string))
        {
            // to ensure "odataContext" is required (not null)
            if (odataContext == null)
            {
                throw new ArgumentNullException("odataContext is a required property for Type18GenericAPIExecuteServicRsResult and cannot be null");
            }
            this.OdataContext = odataContext;
            // to ensure "responseJson" is required (not null)
            if (responseJson == null)
            {
                throw new ArgumentNullException("responseJson is a required property for Type18GenericAPIExecuteServicRsResult and cannot be null");
            }
            this.ResponseJson = responseJson;
        }

        /// <summary>
        /// Gets or Sets OdataContext
        /// </summary>
        [DataMember(Name = "@odata.context", IsRequired = true, EmitDefaultValue = true)]
        public string OdataContext { get; set; }

        /// <summary>
        /// Gets or Sets ResponseJson
        /// </summary>
        [DataMember(Name = "ResponseJson", IsRequired = true, EmitDefaultValue = true)]
        public string ResponseJson { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Type18GenericAPIExecuteServicRsResult {\n");
            sb.Append("  OdataContext: ").Append(OdataContext).Append("\n");
            sb.Append("  ResponseJson: ").Append(ResponseJson).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
