/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// XferAddResponseXferAddRsXferRecXferInfoDebitRef
    /// </summary>
    [DataContract(Name = "XferAdd_response_XferAddRs_XferRec_XferInfo_DebitRef")]
    public partial class XferAddResponseXferAddRsXferRecXferInfoDebitRef : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XferAddResponseXferAddRsXferRecXferInfoDebitRef" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected XferAddResponseXferAddRsXferRecXferInfoDebitRef() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="XferAddResponseXferAddRsXferRecXferInfoDebitRef" /> class.
        /// </summary>
        /// <param name="curAmt">curAmt (required).</param>
        public XferAddResponseXferAddRsXferRecXferInfoDebitRef(XferAddResponseXferAddRsXferRecXferInfoDebitRefCurAmt curAmt = default(XferAddResponseXferAddRsXferRecXferInfoDebitRefCurAmt))
        {
            // to ensure "curAmt" is required (not null)
            if (curAmt == null)
            {
                throw new ArgumentNullException("curAmt is a required property for XferAddResponseXferAddRsXferRecXferInfoDebitRef and cannot be null");
            }
            this.CurAmt = curAmt;
        }

        /// <summary>
        /// Gets or Sets CurAmt
        /// </summary>
        [DataMember(Name = "CurAmt", IsRequired = true, EmitDefaultValue = true)]
        public XferAddResponseXferAddRsXferRecXferInfoDebitRefCurAmt CurAmt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class XferAddResponseXferAddRsXferRecXferInfoDebitRef {\n");
            sb.Append("  CurAmt: ").Append(CurAmt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
