/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// XferAddResponseXferAddRsXferRecXferInfo
    /// </summary>
    [DataContract(Name = "XferAdd_response_XferAddRs_XferRec_XferInfo")]
    public partial class XferAddResponseXferAddRsXferRecXferInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XferAddResponseXferAddRsXferRecXferInfo" /> class.
        /// </summary>
        /// <param name="debitRef">debitRef.</param>
        /// <param name="creditRef">creditRef.</param>
        /// <param name="refData">refData.</param>
        public XferAddResponseXferAddRsXferRecXferInfo(XferAddResponseXferAddRsXferRecXferInfoDebitRef debitRef = default(XferAddResponseXferAddRsXferRecXferInfoDebitRef), XferAddResponseXferAddRsXferRecXferInfoDebitRef creditRef = default(XferAddResponseXferAddRsXferRecXferInfoDebitRef), XferAddResponseXferAddRsXferRecXferInfoRefData refData = default(XferAddResponseXferAddRsXferRecXferInfoRefData))
        {
            this.DebitRef = debitRef;
            this.CreditRef = creditRef;
            this.RefData = refData;
        }

        /// <summary>
        /// Gets or Sets DebitRef
        /// </summary>
        [DataMember(Name = "DebitRef", EmitDefaultValue = false)]
        public XferAddResponseXferAddRsXferRecXferInfoDebitRef DebitRef { get; set; }

        /// <summary>
        /// Gets or Sets CreditRef
        /// </summary>
        [DataMember(Name = "CreditRef", EmitDefaultValue = false)]
        public XferAddResponseXferAddRsXferRecXferInfoDebitRef CreditRef { get; set; }

        /// <summary>
        /// Gets or Sets RefData
        /// </summary>
        [DataMember(Name = "RefData", EmitDefaultValue = false)]
        public XferAddResponseXferAddRsXferRecXferInfoRefData RefData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class XferAddResponseXferAddRsXferRecXferInfo {\n");
            sb.Append("  DebitRef: ").Append(DebitRef).Append("\n");
            sb.Append("  CreditRef: ").Append(CreditRef).Append("\n");
            sb.Append("  RefData: ").Append(RefData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
