/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// XferAddRequestXferAddRqMsgRqHdr
    /// </summary>
    [DataContract(Name = "XferAdd_request_XferAddRq_MsgRqHdr")]
    public partial class XferAddRequestXferAddRqMsgRqHdr : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XferAddRequestXferAddRqMsgRqHdr" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected XferAddRequestXferAddRqMsgRqHdr() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="XferAddRequestXferAddRqMsgRqHdr" /> class.
        /// </summary>
        /// <param name="svcIdent">svcIdent (required).</param>
        /// <param name="feeRqHdr">feeRqHdr.</param>
        public XferAddRequestXferAddRqMsgRqHdr(XferAddRequestXferAddRqMsgRqHdrSvcIdent svcIdent = default(XferAddRequestXferAddRqMsgRqHdrSvcIdent), XferAddRequestXferAddRqMsgRqHdrFeeRqHdr feeRqHdr = default(XferAddRequestXferAddRqMsgRqHdrFeeRqHdr))
        {
            // to ensure "svcIdent" is required (not null)
            if (svcIdent == null)
            {
                throw new ArgumentNullException("svcIdent is a required property for XferAddRequestXferAddRqMsgRqHdr and cannot be null");
            }
            this.SvcIdent = svcIdent;
            this.FeeRqHdr = feeRqHdr;
        }

        /// <summary>
        /// Gets or Sets SvcIdent
        /// </summary>
        [DataMember(Name = "SvcIdent", IsRequired = true, EmitDefaultValue = true)]
        public XferAddRequestXferAddRqMsgRqHdrSvcIdent SvcIdent { get; set; }

        /// <summary>
        /// Gets or Sets FeeRqHdr
        /// </summary>
        [DataMember(Name = "FeeRqHdr", EmitDefaultValue = false)]
        public XferAddRequestXferAddRqMsgRqHdrFeeRqHdr FeeRqHdr { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class XferAddRequestXferAddRqMsgRqHdr {\n");
            sb.Append("  SvcIdent: ").Append(SvcIdent).Append("\n");
            sb.Append("  FeeRqHdr: ").Append(FeeRqHdr).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
