/*
 * exp-openfinance-api
 *
 * Ex  perience API for OpenFinance
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cbd.MobileExperienceApi.Client.FileParameter;
using OpenAPIDateConverter = Cbd.MobileExperienceApi.Client.OpenAPIDateConverter;

namespace Cbd.MobileExperienceApi.Model
{
    /// <summary>
    /// XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef
    /// </summary>
    [DataContract(Name = "XferAdd_request_XferAddRq_XferInfo_ForExDealRef_ForExDealInfo_ForExQuoteRef")]
    public partial class XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef" /> class.
        /// </summary>
        /// <param name="forExQuoteInfo">forExQuoteInfo (required).</param>
        public XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef(List<XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRefForExQuoteInfoInner> forExQuoteInfo = default(List<XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRefForExQuoteInfoInner>))
        {
            // to ensure "forExQuoteInfo" is required (not null)
            if (forExQuoteInfo == null)
            {
                throw new ArgumentNullException("forExQuoteInfo is a required property for XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef and cannot be null");
            }
            this.ForExQuoteInfo = forExQuoteInfo;
        }

        /// <summary>
        /// Gets or Sets ForExQuoteInfo
        /// </summary>
        [DataMember(Name = "ForExQuoteInfo", IsRequired = true, EmitDefaultValue = true)]
        public List<XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRefForExQuoteInfoInner> ForExQuoteInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class XferAddRequestXferAddRqXferInfoForExDealRefForExDealInfoForExQuoteRef {\n");
            sb.Append("  ForExQuoteInfo: ").Append(ForExQuoteInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
